// Auto-generated from sparring decks. Do not edit by hand — re-run sparring-deck-to-toy.py.
// Sources: med=sparring-deck-medida.md, otim=sparring-deck-otimizacao.md

window.CARDS = [
  {
    "id": "med-1",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "σ-algebra: axiomas",
    "hard": false,
    "byRuan": true,
    "ref": "§2",
    "prompt": "Enuncie os três axiomas de uma σ-algebra $\\mathcal{A}$ sobre $X$ e dê um exemplo de coleção que *não* é σ-algebra.",
    "answer": "Prove que todos os finitos subconjuntos de $\\mathbb{N}$ mais $\\mathbb{N}$ formam uma algebra mas não uma σ-algebra. Qual axioma falha?"
  },
  {
    "id": "med-2",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "σ-algebra gerada",
    "hard": false,
    "byRuan": true,
    "ref": "§2",
    "prompt": "Prove que a interseção de uma família arbitrária de σ-algebras é uma σ-algebra. Qual é a consequência para σ-algebras geradas?",
    "answer": "Por que a *reunião* de duas σ-algebras não precisa ser σ-algebra? Dê contraexemplo concreto em $X = \\{1,2,3,4\\}$."
  },
  {
    "id": "med-3",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "Borel σ-algebra",
    "hard": false,
    "byRuan": true,
    "ref": "§2",
    "prompt": "O que é $\\mathcal{B}(\\mathbb{R})$? Cite três famílias geradoras distintas e explique por que todas geram o mesmo objeto.",
    "answer": "É verdade que $\\mathcal{B}(\\mathbb{R}^2) = \\mathcal{B}(\\mathbb{R}) \\otimes \\mathcal{B}(\\mathbb{R})$? Esboce o argumento."
  },
  {
    "id": "med-4",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "σ-algebra: álgebra vs σ-algebra",
    "hard": false,
    "byRuan": false,
    "ref": "§2",
    "prompt": "Qual a diferença formal entre uma álgebra de conjuntos e uma σ-algebra? Dê exemplo de álgebra que não é σ-algebra.",
    "answer": "Construa uma σ-algebra em $\\mathbb{R}$ que não seja $\\{\\emptyset, \\mathbb{R}\\}$, $2^\\mathbb{R}$, nem $\\mathcal{B}(\\mathbb{R})$."
  },
  {
    "id": "med-5",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "σ-algebra: operações",
    "hard": false,
    "byRuan": false,
    "ref": "§2",
    "prompt": "Se $\\mathcal{A}$ é σ-algebra e $\\{A_n\\} \\subset \\mathcal{A}$, mostre que $\\limsup_n A_n$ e $\\liminf_n A_n$ pertencem a $\\mathcal{A}$.",
    "answer": "$\\limsup A_n = \\bigcap_k \\bigcup_{n \\ge k} A_n$ e $\\liminf A_n = \\bigcup_k \\bigcap_{n \\ge k} A_n$. Qual representa \"infinitely often\" e qual \"eventually always\"?"
  },
  {
    "id": "med-6",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "função mensurável: caracterizações",
    "hard": false,
    "byRuan": true,
    "ref": "§2",
    "prompt": "Dê quatro caracterizações equivalentes de $f:(X,\\mathcal{A}) \\to (\\mathbb{R},\\mathcal{B})$ mensurável.",
    "answer": "Por que $\\{f > a\\}$ para todo $a$ basta? Trace o argumento: o conjunto $\\{B : f^{-1}(B) \\in \\mathcal{A}\\}$ é σ-algebra, portanto..."
  },
  {
    "id": "med-7",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "limites de funções mensuráveis",
    "hard": false,
    "byRuan": true,
    "ref": "§2",
    "prompt": "Se $\\{f_n\\}$ são mensuráveis, prove que $\\sup_n f_n$, $\\limsup f_n$, $\\liminf f_n$ são mensuráveis.",
    "answer": "É verdade que limites pontuais de funções contínuas são contínuos? E mensuráveis? O que isso revela sobre mensurábildade?"
  },
  {
    "id": "med-8",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "composição e mensurabilidade",
    "hard": false,
    "byRuan": true,
    "ref": "§2",
    "prompt": "$f:(X,\\mathcal{A}) \\to \\mathbb{R}$ mensurável, $g:\\mathbb{R} \\to \\mathbb{R}$ contínua. $g \\circ f$ é mensurável? E $f \\circ g$? Cuidado com a direção.",
    "answer": "Dê exemplo onde $f$ é Lebesgue-mensurável e $g$ é contínua mas $f \\circ g$ não é Lebesgue-mensurável. (Dica: escada de Cantor.)"
  },
  {
    "id": "med-9",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "funções simples",
    "hard": false,
    "byRuan": false,
    "ref": "§2",
    "prompt": "Defina função simples. Prove que toda $f \\ge 0$ mensurável é limite monótono crescente de funções simples.",
    "answer": "Construa explicitamente a sequência $\\varphi_n \\nearrow f$ para $f(x) = e^x$ em $[0,1]$. Qual é a taxa de convergência?"
  },
  {
    "id": "med-10",
    "topic": "σ-Algebras e Funções Mensuráveis (Bartle Cap 2)",
    "title": "Borel vs Lebesgue",
    "hard": false,
    "byRuan": false,
    "ref": "§2",
    "prompt": "Por que existem funções Lebesgue-mensuráveis que não são Borel-mensuráveis? Argumento de cardinalidade.",
    "answer": "$|\\mathcal{B}(\\mathbb{R})| = \\mathfrak{c}$ e $|\\mathcal{L}(\\mathbb{R})| = 2^\\mathfrak{c}$. Por que todo subconjunto do conjunto de Cantor é Lebesgue-mensurável?"
  },
  {
    "id": "med-11",
    "topic": "Medidas (Bartle Cap 3)",
    "title": "espaço de medida",
    "hard": false,
    "byRuan": false,
    "ref": "§3",
    "prompt": "Defina medida $\\mu$ em $(X, \\mathcal{A})$. Quais são as duas propriedades axiomáticas? O que é continuidade de medida pelo baixo e pelo alto?",
    "answer": "Prove continuidade pelo alto *sem* assumir $\\mu(A_1) < \\infty$. Qual hipótese adicional é necessária? Dê contraexemplo sem ela."
  },
  {
    "id": "med-12",
    "topic": "Medidas (Bartle Cap 3)",
    "title": "medida: propriedades básicas",
    "hard": false,
    "byRuan": false,
    "ref": "§3",
    "prompt": "Enuncie e prove: $\\mu(\\emptyset) = 0$, monotonia, subaditividade countable, e $\\mu(A \\setminus B) = \\mu(A) - \\mu(B)$ quando $B \\subset A$ e $\\mu(B) < \\infty$.",
    "answer": "Por que a hipótese $\\mu(B) < \\infty$ é necessária para $\\mu(A \\setminus B) = \\mu(A) - \\mu(B)$? Dê contraexemplo com $\\mu = $ medida de contagem."
  },
  {
    "id": "med-13",
    "topic": "Medidas (Bartle Cap 3)",
    "title": "conjunto nulo e completude",
    "hard": false,
    "byRuan": false,
    "ref": "§3",
    "prompt": "O que é conjunto $\\mu$-nulo? O que é espaço de medida *completo*? A medida de Lebesgue é completa? A medida de Borel?",
    "answer": "Exiba subconjunto do conjunto de Cantor que é Lebesgue-mensurável (de medida zero) mas não Borel-mensurável."
  },
  {
    "id": "med-14",
    "topic": "Medidas (Bartle Cap 3)",
    "title": "a.e. (quase em todo ponto)",
    "hard": false,
    "byRuan": false,
    "ref": "§3",
    "prompt": "Defina \"propriedade $P$ vale $\\mu$-quase em todo ponto (a.e.)\". Se $f = g$ a.e. e $\\int f < \\infty$, o que se pode concluir sobre $\\int g$?",
    "answer": "Encontre $f, g: \\mathbb{R} \\to \\mathbb{R}$ com $f = g$ a.e. (Lebesgue), $f$ mensurável, mas $g$ não mensurável."
  },
  {
    "id": "med-15",
    "topic": "Medidas (Bartle Cap 3)",
    "title": "medidas σ-finitas",
    "hard": false,
    "byRuan": false,
    "ref": "§3",
    "prompt": "Defina medida σ-finita. Dê dois exemplos que são σ-finitas e um exemplo que não é.",
    "answer": "Por que σ-finitude é hipótese em Radon–Nikodym e Fubini? Construa um contra-exemplo para Radon-Nikodym sem σ-finitude."
  },
  {
    "id": "med-16",
    "topic": "Medidas (Bartle Cap 3)",
    "title": "medida de Lebesgue",
    "hard": false,
    "byRuan": false,
    "ref": "§3, Cap 9",
    "prompt": "Enuncie a existência da medida de Lebesgue $\\lambda$ em $\\mathbb{R}$. Quais são suas propriedades caracterizantes?",
    "answer": "Por que não existe medida em todos os subconjuntos de $\\mathbb{R}$ que seja translação-invariante e assigne comprimento 1 a $[0,1]$? (Conjunto de Vitali.)"
  },
  {
    "id": "med-17",
    "topic": "Integral (Bartle Cap 4)",
    "title": "integral de função simples",
    "hard": false,
    "byRuan": false,
    "ref": "§4",
    "prompt": "Defina $\\int \\varphi \\, d\\mu$ para função simples $\\varphi = \\sum_{i=1}^n a_i \\mathbf{1}_{E_i}$ com $a_i \\ge 0$. Por que precisamos que a representação seja canônica?",
    "answer": "Mostre que a integral de função simples não depende da representação (i.e., é bem definida). Onde entra a aditividade de $\\mu$?"
  },
  {
    "id": "med-18",
    "topic": "Integral (Bartle Cap 4)",
    "title": "integral de função não-negativa",
    "hard": false,
    "byRuan": false,
    "ref": "§4",
    "prompt": "Defina $\\int f \\, d\\mu$ para $f \\ge 0$ mensurável via supremo sobre funções simples. Enuncie as propriedades básicas: monotonia, linearidade, $\\int_E f = \\int f \\mathbf{1}_E$.",
    "answer": "Se $f = 0$ a.e., mostre $\\int f = 0$. E a recíproca: se $f \\ge 0$ mensurável e $\\int f = 0$, então $f = 0$ a.e.?"
  },
  {
    "id": "med-19",
    "topic": "Integral (Bartle Cap 4)",
    "title": "Teorema da Convergência Monótona (MCT)",
    "hard": false,
    "byRuan": true,
    "ref": "§4 (Teorema 4.6)",
    "prompt": "Enuncie o MCT com todas as hipóteses. Esboce a prova.",
    "answer": "Por que a hipótese de não-negatividade é necessária? Exiba $f_n \\nearrow f$ mensurável com $\\int f_n \\not\\to \\int f$ quando $f_n$ podem ser negativas."
  },
  {
    "id": "med-20",
    "topic": "Integral (Bartle Cap 4)",
    "title": "MCT: hipóteses são apertadas",
    "hard": false,
    "byRuan": false,
    "ref": "§4",
    "prompt": "Qual das três hipóteses do MCT (não-negatividade / mensurabilidade / monotonicidade a.e.) pode ser enfraquecida para \"a.e.\" sem perda? O que acontece ao remover cada uma?",
    "answer": "Para cada hipótese, construa sequência que viola só ela e onde a conclusão $\\int f_n \\to \\int f$ falha."
  },
  {
    "id": "med-21",
    "topic": "Integral (Bartle Cap 4)",
    "title": "Lema de Fatou",
    "hard": false,
    "byRuan": true,
    "ref": "§4 (Teorema 4.8 / Corollary 4.9)",
    "prompt": "Enuncie Fatou. Dê sequência onde a desigualdade é estrita.",
    "answer": "Prove Fatou a partir do MCT: aplique MCT a $g_k(x) = \\inf_{n \\ge k} f_n(x)$."
  },
  {
    "id": "med-22",
    "topic": "Integral (Bartle Cap 4)",
    "title": "Fatou: direção da desigualdade",
    "hard": false,
    "byRuan": false,
    "ref": "§4",
    "prompt": "$\\int \\liminf f_n \\le \\liminf \\int f_n$. Por que a desigualdade vai nessa direção e não na oposta? Intuição de \"massa escapando\".",
    "answer": "Existe um análogo de Fatou para $\\limsup$? Em que condições vale $\\limsup \\int f_n \\le \\int \\limsup f_n$?"
  },
  {
    "id": "med-23",
    "topic": "Integral (Bartle Cap 4)",
    "title": "MCT → Fatou → DCT: cadeia de provas",
    "hard": false,
    "byRuan": false,
    "ref": "§4–5",
    "prompt": "Descreva a cadeia MCT → Fatou → DCT em uma linha por seta: o que cada passo usa do anterior.",
    "answer": "Prove DCT a partir de Fatou: aplique Fatou a $g + f_n$ e $g - f_n$, onde $g$ é a dominante."
  },
  {
    "id": "med-24",
    "topic": "Funções Integráveis e DCT (Bartle Cap 5)",
    "title": "DCT (Dominated Convergence Theorem)",
    "hard": false,
    "byRuan": true,
    "ref": "§5 (Teorema 5.6)",
    "prompt": "Enuncie o DCT. Qual é a \"armadilha\" mais comum na aplicação?",
    "answer": "A condição $|f_n| \\le g$ a.e. para **todo** $n$ com $g$ **fixo** integrable — reformule isso como condição sobre $\\sup_n f_n$. O que muda se $g$ depende de $n$?"
  },
  {
    "id": "med-25",
    "topic": "Funções Integráveis e DCT (Bartle Cap 5)",
    "title": "DCT: contraexemplo canônico",
    "hard": false,
    "byRuan": false,
    "ref": "§5",
    "prompt": "Mostre que $f_n = n \\mathbf{1}_{[0,1/n]}$ viola a conclusão do DCT. Qual hipótese falha?",
    "answer": "Modifique o exemplo para ter $f_n \\to 0$ uniformemente (não apenas pontualmente). A conclusão do DCT passa a valer? Por quê?"
  },
  {
    "id": "med-26",
    "topic": "Funções Integráveis e DCT (Bartle Cap 5)",
    "title": "integrabilidade e linearidade",
    "hard": false,
    "byRuan": false,
    "ref": "§5",
    "prompt": "Defina $f \\in L^1(\\mu)$. Prove que $L^1$ é espaço vetorial e que a integral é funcional linear.",
    "answer": "Se $f, g \\in L^1$ e $f \\le g$ a.e., prove $\\int f \\le \\int g$. O que acontece se trocamos $\\le$ por $<$ em um conjunto de medida positiva?"
  },
  {
    "id": "med-27",
    "topic": "Funções Integráveis e DCT (Bartle Cap 5)",
    "title": "integração em conjuntos e funções indicadoras",
    "hard": false,
    "byRuan": false,
    "ref": "§5",
    "prompt": "Defina $\\int_E f \\, d\\mu$. Prove que se $\\mu(E) = 0$ então $\\int_E f \\, d\\mu = 0$ para todo $f$ mensurável.",
    "answer": "Seja $f$ mensurável, $f \\ge 0$. Se $\\int_E f \\, d\\mu = 0$ para todo mensurável $E$, o que se conclui sobre $f$?"
  },
  {
    "id": "med-28",
    "topic": "Funções Integráveis e DCT (Bartle Cap 5)",
    "title": "DCT generalizado (convergência em L¹)",
    "hard": false,
    "byRuan": false,
    "ref": "§5",
    "prompt": "O DCT dá $\\int f_n \\to \\int f$. Existe versão mais forte que dá $\\int |f_n - f| \\to 0$?",
    "answer": "Prove que DCT implica $\\|f_n - f\\|_1 \\to 0$. (Aplique DCT à sequência $|f_n - f|$, dominada por $2g$.)"
  },
  {
    "id": "med-29",
    "topic": "Funções Integráveis e DCT (Bartle Cap 5)",
    "title": "integral como função de conjunto",
    "hard": false,
    "byRuan": false,
    "ref": "§5",
    "prompt": "Defina $\\nu(E) = \\int_E f \\, d\\mu$ para $f \\ge 0$ mensurável. Prove que $\\nu$ é medida.",
    "answer": "O que é $\\nu$ quando $f$ pode ser negativa (função integrável signed)? Que condição assegura que $\\nu$ é medida com sinal?"
  },
  {
    "id": "med-30",
    "topic": "Funções Integráveis e DCT (Bartle Cap 5)",
    "title": "convergência e integração: panorama",
    "hard": false,
    "byRuan": false,
    "ref": "§4–5, §7",
    "prompt": "Organize: sob quais condições $f_n \\to f$ implica $\\int f_n \\to \\int f$? Liste MCT / Fatou / DCT / convergência uniforme em espaço de medida finita.",
    "answer": "No contexto de medida finita, $f_n \\to f$ uniformemente implica $\\int f_n \\to \\int f$ sem dominator? Prove ou dê contraexemplo."
  },
  {
    "id": "med-31",
    "topic": "Espaços $L^p$ (Bartle Cap 6)",
    "title": "Hölder e Minkowski",
    "hard": false,
    "byRuan": true,
    "ref": "§6 (6.2, 6.3)",
    "prompt": "Enuncie Hölder e Minkowski. Qual é a condição de expoentes conjugados?",
    "answer": "Prove a desigualdade de Hölder via desigualdade de Young: $ab \\le \\frac{a^p}{p} + \\frac{b^q}{q}$ para $a,b \\ge 0$, $1/p + 1/q = 1$."
  },
  {
    "id": "med-32",
    "topic": "Espaços $L^p$ (Bartle Cap 6)",
    "title": "completude de $L^p$",
    "hard": false,
    "byRuan": true,
    "ref": "§6 (Teorema 6.6, Riesz–Fischer)",
    "prompt": "Esboce a prova de que $L^p$ é completo ($1 \\le p < \\infty$). Qual é o \"truque do chapéu\"?",
    "answer": "O argumento usa MCT para dominar; onde exatamente? Identifique o passo que transfere convergência a.e. para convergência em $L^p$."
  },
  {
    "id": "med-33",
    "topic": "Espaços $L^p$ (Bartle Cap 6)",
    "title": "inclusões entre $L^p$",
    "hard": false,
    "byRuan": true,
    "ref": "§6",
    "prompt": "Em espaço de medida finita, qual é a relação de inclusão entre $L^p$ e $L^q$ para $p \\le q$? O que muda quando $\\mu(X) = \\infty$?",
    "answer": "Construa $f \\in L^1(\\mathbb{R}) \\setminus L^2(\\mathbb{R})$ e $g \\in L^2(\\mathbb{R}) \\setminus L^1(\\mathbb{R})$. Para qual tipo de singularidade cada um viola o outro espaço?"
  },
  {
    "id": "med-34",
    "topic": "Espaços $L^p$ (Bartle Cap 6)",
    "title": "$L^\\infty$ e norma essencial",
    "hard": false,
    "byRuan": false,
    "ref": "§6",
    "prompt": "Defina $L^\\infty(\\mu)$ e $\\|f\\|_\\infty$. Prove que $\\|f\\|_\\infty = 0 \\Leftrightarrow f = 0$ a.e.",
    "answer": "Hölder com $p = 1, q = \\infty$ diz $|\\int fg| \\le \\|f\\|_1 \\|g\\|_\\infty$. Quando a igualdade vale?"
  },
  {
    "id": "med-35",
    "topic": "Espaços $L^p$ (Bartle Cap 6)",
    "title": "densidade em $L^p$",
    "hard": false,
    "byRuan": false,
    "ref": "§6",
    "prompt": "Cite dois subconjuntos densos em $L^p(\\mathbb{R}, \\lambda)$ para $1 \\le p < \\infty$. Por que $L^2$ é separável?",
    "answer": "As funções simples com suporte de medida finita são densas em $L^p$? E as funções contínuas com suporte compacto? Esboce o argumento."
  },
  {
    "id": "med-36",
    "topic": "Espaços $L^p$ (Bartle Cap 6)",
    "title": "dual de $L^p$",
    "hard": false,
    "byRuan": false,
    "ref": "§6, §8",
    "prompt": "Enuncie o teorema de representação de Riesz para $(L^p)^*$: o dual de $L^p$ é $L^q$ para $1 < p < \\infty$. Qual é o papel de Radon–Nikodym aqui?",
    "answer": "O dual de $L^1$ é $L^\\infty$? E o dual de $L^\\infty$? Qual o papel da σ-finitude?"
  },
  {
    "id": "med-37",
    "topic": "Modos de Convergência (Bartle Cap 7)",
    "title": "três modos de convergência",
    "hard": false,
    "byRuan": false,
    "ref": "§7",
    "prompt": "Defina: convergência quase em todo ponto (a.e.), convergência em medida, convergência em $L^p$. Escreva as definições formais com quantificadores.",
    "answer": "Organize em diagrama quais implicações valem (e quais não) entre os três modos. Para cada implicação faltante, dê contraexemplo."
  },
  {
    "id": "med-38",
    "topic": "Modos de Convergência (Bartle Cap 7)",
    "title": "a.e. vs em medida",
    "hard": false,
    "byRuan": false,
    "ref": "§7",
    "prompt": "$f_n \\to f$ em medida implica convergência a.e. de alguma *subsequência*. Enuncie este resultado e esboce a prova.",
    "answer": "A sequência \"typewriter\" $f_n = \\mathbf{1}_{[\\frac{k}{2^m}, \\frac{k+1}{2^m}]}$ converge em medida mas não a.e. Descreva a sequência e verifique ambas as afirmações."
  },
  {
    "id": "med-39",
    "topic": "Modos de Convergência (Bartle Cap 7)",
    "title": "Egorov",
    "hard": false,
    "byRuan": true,
    "ref": "§7",
    "prompt": "Enuncie Egorov. Qual hipótese é essencial (e frequentemente esquecida)?",
    "answer": "Construa $f_n \\to 0$ a.e. em $\\mathbb{R}$ (com medida de Lebesgue) onde a conclusão de Egorov falha. Por que a medida finita é necessária?"
  },
  {
    "id": "med-40",
    "topic": "Modos de Convergência (Bartle Cap 7)",
    "title": "Lusin",
    "hard": false,
    "byRuan": true,
    "ref": "§7",
    "prompt": "Enuncie Lusin (terceiro princípio de Littlewood). O que diz sobre mensurabilidade e continuidade?",
    "answer": "Se $f$ é mensurável (Lebesgue) em $[0,1]$ e $\\epsilon = 0.01$, Lusin garante... escreva o enunciado concreto. Implica que $f$ é contínua em quase todo ponto? Discuta."
  },
  {
    "id": "med-41",
    "topic": "Modos de Convergência (Bartle Cap 7)",
    "title": "convergência em $L^p$ vs em medida",
    "hard": false,
    "byRuan": false,
    "ref": "§7",
    "prompt": "$\\|f_n - f\\|_p \\to 0$ implica $f_n \\to f$ em medida? E a recíproca?",
    "answer": "Se $f_n \\to f$ em $L^p$ com $1 \\le p < \\infty$, existe subsequência convergindo a.e.? Prove."
  },
  {
    "id": "med-42",
    "topic": "Decomposição de Medidas (Bartle Cap 8)",
    "title": "decomposição de Hahn",
    "hard": false,
    "byRuan": false,
    "ref": "§8",
    "prompt": "Enuncie o Teorema de Decomposição de Hahn para medida com sinal. O que é a decomposição de Jordan?",
    "answer": "A decomposição de Hahn $(P, N)$ é única? Em qual sentido? Dê exemplo onde dois pares diferentes são igualmente válidos."
  },
  {
    "id": "med-43",
    "topic": "Decomposição de Medidas (Bartle Cap 8)",
    "title": "absolutamente contínuo vs singular",
    "hard": false,
    "byRuan": false,
    "ref": "§8",
    "prompt": "Defina $\\nu \\ll \\mu$ (absolutamente contínuo) e $\\nu \\perp \\mu$ (singular). Dê exemplo de par $(\\nu, \\mu)$ em cada categoria.",
    "answer": "A função de Cantor gera uma medida singular em relação à Lebesgue. Descreva essa medida e verifique que ela é singular."
  },
  {
    "id": "med-44",
    "topic": "Decomposição de Medidas (Bartle Cap 8)",
    "title": "Radon–Nikodym",
    "hard": false,
    "byRuan": true,
    "ref": "§8 (Teorema 8.9)",
    "prompt": "Enuncie Radon–Nikodym. Por que σ-finitude é indispensável? Dê contraexemplo.",
    "answer": "Prove unicidade da derivada de Radon–Nikodym. (Se $\\nu(E) = \\int_E f \\, d\\mu = \\int_E g \\, d\\mu$ para todo $E$, então $f = g$ a.e.)"
  },
  {
    "id": "med-45",
    "topic": "Decomposição de Medidas (Bartle Cap 8)",
    "title": "Radon–Nikodym em probabilidade",
    "hard": false,
    "byRuan": true,
    "ref": "§8",
    "prompt": "Conecte Radon–Nikodym a densidades de probabilidade (pdf). O que significa $\\mathbb{P}(X \\in E) = \\int_E f \\, d\\lambda$ em linguagem de medida?",
    "answer": "Defina esperança condicional $\\mathbb{E}[Y | \\mathcal{G}]$ via Radon–Nikodym. Qual a medida dominante e qual a absolutamente contínua nessa construção?"
  },
  {
    "id": "med-46",
    "topic": "Decomposição de Medidas (Bartle Cap 8)",
    "title": "decomposição de Lebesgue",
    "hard": false,
    "byRuan": false,
    "ref": "§8",
    "prompt": "Enuncie a Decomposição de Lebesgue: toda $\\nu$ σ-finita se escreve como $\\nu = \\nu_{ac} + \\nu_s$ com $\\nu_{ac} \\ll \\mu$ e $\\nu_s \\perp \\mu$. A decomposição é única?",
    "answer": "Para $\\mu = $ Lebesgue e $\\nu$ com função de distribuição $F(x) = \\frac{1}{2}x \\mathbf{1}_{[0,1]} + \\frac{1}{2}F_C(x)$ (onde $F_C$ é função de Cantor), identifique $\\nu_{ac}$ e $\\nu_s$."
  },
  {
    "id": "med-47",
    "topic": "Geração de Medidas (Bartle Cap 9)",
    "title": "conteúdo e pré-medida",
    "hard": false,
    "byRuan": false,
    "ref": "§9",
    "prompt": "O que é uma pré-medida (conteúdo σ-aditivo) em uma álgebra? Por que não basta ter aditividade finita?",
    "answer": "Dê exemplo de conteúdo finitamente aditivo em uma álgebra que não é σ-aditivo. (Dica: álgebra de conjuntos com limites finitos de medida em $\\mathbb{N}$.)"
  },
  {
    "id": "med-48",
    "topic": "Geração de Medidas (Bartle Cap 9)",
    "title": "Extensão de Carathéodory",
    "hard": false,
    "byRuan": false,
    "ref": "§9 (Teorema 9.3)",
    "prompt": "Enuncie o Teorema de Extensão de Carathéodory (apenas o enunciado — a prova está fora do escopo do sprint). O que significa \"extensão única\"?",
    "answer": "Por que a unicidade requer σ-finitude? Construa (ao menos esboce) dois exemplos de extensões distintas de uma pré-medida sem σ-finitude."
  },
  {
    "id": "med-49",
    "topic": "Geração de Medidas (Bartle Cap 9)",
    "title": "medida de Lebesgue via extensão",
    "hard": false,
    "byRuan": false,
    "ref": "§9",
    "prompt": "Como a medida de Lebesgue em $\\mathbb{R}$ é construída via Carathéodory? Qual é a álgebra inicial e qual é a pré-medida?",
    "answer": "Por que todo conjunto Borel é Lebesgue-mensurável mas não vice-versa? O que a construção via Carathéodory adiciona além dos Borel?"
  },
  {
    "id": "med-50",
    "topic": "Medidas Produto e Fubini–Tonelli (Bartle Cap 10)",
    "title": "produto de medidas",
    "hard": false,
    "byRuan": false,
    "ref": "§10",
    "prompt": "Defina a medida produto $\\mu \\otimes \\nu$ em $(X \\times Y, \\mathcal{A} \\otimes \\mathcal{B})$. Existe e é única sob quais hipóteses?",
    "answer": "Calcule $(\\lambda \\otimes \\lambda)([0,1] \\times [0,1])$ usando a definição via retângulos mensuráveis. Depois confirme via Fubini."
  },
  {
    "id": "med-51",
    "topic": "Medidas Produto e Fubini–Tonelli (Bartle Cap 10)",
    "title": "Tonelli vs Fubini",
    "hard": false,
    "byRuan": true,
    "ref": "§10 (Teoremas 10.5, 10.7)",
    "prompt": "Distinga Tonelli de Fubini. Qual hipótese difere?",
    "answer": "Qual é o workflow correto para trocar integrais iteradas para $f$ com sinal? (Primeiro Tonelli em $|f|$, depois Fubini em $f$ — descreva a razão de cada passo.)"
  },
  {
    "id": "med-52",
    "topic": "Medidas Produto e Fubini–Tonelli (Bartle Cap 10)",
    "title": "Fubini: contraexemplo",
    "hard": false,
    "byRuan": true,
    "ref": "§10",
    "prompt": "Dê contraexemplo onde as integrais iteradas existem e diferem (hipótese de Fubini viola).",
    "answer": "O exemplo $f(x,y) = (x^2 - y^2)/(x^2+y^2)^2$ em $[0,1]^2$ tem $\\int_0^1 \\int_0^1 f \\, dy \\, dx = \\pi/4$ mas $\\int_0^1 \\int_0^1 f \\, dx \\, dy = -\\pi/4$. Verifique que $\\int |f| = \\infty$."
  },
  {
    "id": "med-53",
    "topic": "Medidas Produto e Fubini–Tonelli (Bartle Cap 10)",
    "title": "seções de funções mensuráveis",
    "hard": false,
    "byRuan": false,
    "ref": "§10",
    "prompt": "Se $f: X \\times Y \\to \\mathbb{R}$ é $(\\mathcal{A} \\otimes \\mathcal{B})$-mensurável, prove que a seção $f_x: Y \\to \\mathbb{R}$, $f_x(y) = f(x,y)$, é $\\mathcal{B}$-mensurável para $\\mu$-q.t. $x$.",
    "answer": "O que pode dar errado se $f$ é apenas $\\mathcal{A}$-mensurável (não produto-mensurável)? Esboce onde a mensurabilidade das seções entra na prova de Fubini."
  },
  {
    "id": "med-54",
    "topic": "Medidas Produto e Fubini–Tonelli (Bartle Cap 10)",
    "title": "Fubini e integrais iteradas em probabilidade",
    "hard": false,
    "byRuan": false,
    "ref": "§10",
    "prompt": "$X, Y$ variáveis aleatórias independentes com densidades $f_X, f_Y$. Expresse $\\mathbb{E}[g(X,Y)]$ via Fubini. Que hipótese justifica a troca de integrais?",
    "answer": "Se $X$ e $Y$ são independentes e $\\mathbb{E}[|X|], \\mathbb{E}[|Y|] < \\infty$, prove $\\mathbb{E}[XY] = \\mathbb{E}[X]\\mathbb{E}[Y]$."
  },
  {
    "id": "med-55",
    "topic": "Borel–Cantelli e Modos de Convergência (tópicos transversais)",
    "title": "Borel–Cantelli",
    "hard": false,
    "byRuan": true,
    "ref": "§3, §7",
    "prompt": "Enuncie os dois lemas de Borel–Cantelli. Cite uma aplicação probabilística de cada.",
    "answer": "BC1 diz $\\mu(\\limsup A_n) = 0$ quando $\\sum \\mu(A_n) < \\infty$. Esboce a prova usando continuidade de medida pelo alto e subaditividade countable."
  },
  {
    "id": "med-56",
    "topic": "Borel–Cantelli e Modos de Convergência (tópicos transversais)",
    "title": "Borel–Cantelli: limsup vs união",
    "hard": false,
    "byRuan": false,
    "ref": "§3",
    "prompt": "Por que BC1 conclui $\\mu(\\limsup A_n) = 0$ e **não** $\\mu(\\bigcup A_n) = 0$? Dê exemplo onde $\\mu(\\bigcup A_n) > 0$ mas $\\mu(\\limsup A_n) = 0$.",
    "answer": "Construa $A_n \\subset [0,1]$ com $\\sum \\lambda(A_n) < \\infty$ tal que $\\bigcup A_n = [0,1]$."
  },
  {
    "id": "med-57",
    "topic": "Borel–Cantelli e Modos de Convergência (tópicos transversais)",
    "title": "diferenciação de Lebesgue",
    "hard": false,
    "byRuan": true,
    "ref": "Cap 9–10 (contexto), §7",
    "prompt": "Enuncie o Teorema de Diferenciação de Lebesgue. Como se conecta ao Teorema Fundamental do Cálculo?",
    "answer": "Para $f \\in L^1_\\text{loc}$, o que é um ponto de Lebesgue? Qual proporção dos pontos são pontos de Lebesgue?"
  },
  {
    "id": "med-58",
    "topic": "Probabilidade e SOC (conexões)",
    "title": "espaço de probabilidade",
    "hard": false,
    "byRuan": true,
    "ref": "§8",
    "prompt": "Defina espaço de probabilidade. Defina $\\sigma(X)$ para uma variável aleatória $X$ e explique $\\mathbb{E}[Y | \\mathcal{G}]$ em linguagem de medida.",
    "answer": "Prove que $\\mathbb{E}[\\mathbb{E}[Y|\\mathcal{G}]] = \\mathbb{E}[Y]$ usando apenas a definição de esperança condicional via Radon–Nikodym."
  },
  {
    "id": "med-59",
    "topic": "Probabilidade e SOC (conexões)",
    "title": "SAA e convergência",
    "hard": false,
    "byRuan": true,
    "ref": "§5, §7 (SLLN via DCT/BC)",
    "prompt": "Por que SAA (Sample Average Approximation) tem justificativa via teoria da medida? Que tipo de convergência está em jogo?",
    "answer": "SLLN para $f_n = c(u, \\varepsilon_i)$ fixado $u$: qual é o espaço de probabilidade, qual a variável aleatória, e qual a hipótese de integrabilidade?"
  },
  {
    "id": "med-60",
    "topic": "Probabilidade e SOC (conexões)",
    "title": "integral de Lebesgue vs Riemann",
    "hard": false,
    "byRuan": false,
    "ref": "§1, §4",
    "prompt": "Dê três situações onde a integral de Lebesgue existe mas a de Riemann não. Qual é o critério de Lebesgue para integrabilidade Riemann?",
    "answer": "A função de Dirichlet $\\mathbf{1}_\\mathbb{Q}$ é Lebesgue-integrável em $[0,1]$? E Riemann-integrável? Calcule a integral de Lebesgue."
  },
  {
    "id": "med-61",
    "topic": "Probabilidade e SOC (conexões)",
    "title": "troca de limite e integral: checklist",
    "hard": false,
    "byRuan": false,
    "ref": "§4–5",
    "prompt": "Antes de escrever $\\lim_n \\int f_n = \\int \\lim_n f_n$, quais condições você deve verificar? Liste em ordem de verificação prática.",
    "answer": "Construa uma situação em exame onde o enunciado pede para provar a troca, com três hipóteses dadas. Identifique qual teorema se aplica e quais hipóteses deve verificar."
  },
  {
    "id": "med-62",
    "topic": "Integração em Espaços Gerais",
    "title": "medida de contagem",
    "hard": false,
    "byRuan": false,
    "ref": "§3, §4",
    "prompt": "Defina a medida de contagem $\\#$ em $(\\mathbb{N}, 2^\\mathbb{N})$. O que é $\\int f \\, d\\#$? Quando $f \\in L^1(\\#)$?",
    "answer": "MCT para medida de contagem: enuncie e prove como consequência de MCT abstrato. Como se relaciona com a convergência monotóna de séries?"
  },
  {
    "id": "med-63",
    "topic": "Integração em Espaços Gerais",
    "title": "imagem de medida (pushforward)",
    "hard": false,
    "byRuan": false,
    "ref": "§4–5",
    "prompt": "Defina a imagem $T_*\\mu$ de uma medida $\\mu$ pela transformação mensurável $T: (X,\\mathcal{A}) \\to (Y, \\mathcal{B})$. Enuncie a fórmula de mudança de variáveis.",
    "answer": "Para $T(x) = x^2$ em $([0,\\infty), \\mathcal{B}, \\lambda)$, compute $T_*\\lambda$ via a fórmula. O que é a densidade de $T_*\\lambda$ em relação a $\\lambda$?"
  },
  {
    "id": "med-64",
    "topic": "Integração em Espaços Gerais",
    "title": "integral em subconjunto",
    "hard": false,
    "byRuan": false,
    "ref": "§4",
    "prompt": "Se $(X, \\mathcal{A}, \\mu)$ é espaço de medida e $E \\in \\mathcal{A}$ com $\\mu(E) > 0$, o espaço $(E, \\mathcal{A}|_E, \\mu|_E)$ é espaço de medida? $\\int_E f \\, d\\mu$ coincide com $\\int f \\, d\\mu|_E$?",
    "answer": "Compute $\\int_{[0,1]} e^x \\, d\\lambda$ e $\\int_{[1,2]} e^x \\, d\\lambda$ e deduza $\\int_{[0,2]} e^x \\, d\\lambda$ sem reintegrar."
  },
  {
    "id": "med-65",
    "topic": "Integração em Espaços Gerais",
    "title": "funções características e integrais iteradas",
    "hard": false,
    "byRuan": false,
    "ref": "§10",
    "prompt": "Seja $E \\in \\mathcal{A} \\otimes \\mathcal{B}$ (produto mensurável). Mostre que $\\mu(\\{x: E_x \\ne \\emptyset\\})$ é mensurável, onde $E_x = \\{y: (x,y) \\in E\\}$.",
    "answer": "Como seções de conjuntos se relacionam com seções de funções? Use isso para enunciar Tonelli para funções indicadoras."
  },
  {
    "id": "med-66",
    "topic": "Erros Clássicos de Exame",
    "title": "DCT com dominante dependente de $n$",
    "hard": false,
    "byRuan": false,
    "ref": "§5",
    "prompt": "\"Seja $g_n$ tal que $|f_n| \\le g_n$ a.e. e $\\int g_n \\to \\int g < \\infty$. Posso trocar limite e integral?\" Isso é DCT?",
    "answer": "Não é DCT padrão, mas é o **Generalized DCT** (Vitali). Enuncie-o. Qual é a hipótese extra? Dê exemplo onde $|f_n| \\le g_n$ com $g_n \\to g$ a.e. e $\\int g_n \\to \\int g$, mas $\\int f_n \\not\\to \\int f$ (se a hipótese falha de outra forma)."
  },
  {
    "id": "med-67",
    "topic": "Erros Clássicos de Exame",
    "title": "a.e. vs em todo ponto",
    "hard": false,
    "byRuan": false,
    "ref": "§3",
    "prompt": "\"$f = g$ a.e. e $f(x_0) = 0$, portanto $g(x_0) = 0$.\" Correto?",
    "answer": "Construa $f = 0$ a.e. e $g$ com $g(0) = 1$ mas $f = g$ a.e. em $\\mathbb{R}$. O que a.e. diz e o que não diz sobre pontos individuais?"
  },
  {
    "id": "med-68",
    "topic": "Erros Clássicos de Exame",
    "title": "Fubini com função signed",
    "hard": false,
    "byRuan": false,
    "ref": "§10",
    "prompt": "\"$f(x,y) \\ge 0$, então posso usar Fubini.\" Correto? Qual teorema usar para $f \\ge 0$?",
    "answer": "\"$\\int |f| < \\infty$\" e \"$f \\ge 0$\" — como se relacionam como hipóteses para trocar integrais iteradas? Esboce os dois caminhos possíveis em forma de árvore de decisão."
  },
  {
    "id": "med-69",
    "topic": "Erros Clássicos de Exame",
    "title": "convergência em medida não implica a.e.",
    "hard": false,
    "byRuan": false,
    "ref": "§7",
    "prompt": "Construa explicitamente a sequência \"typewriter\" que converge em medida para 0 mas não converge em nenhum ponto de $[0,1]$.",
    "answer": "Por que a sequência typewriter falha em ter limite a.e.? O que acontece com qualquer subsequência fixa?"
  },
  {
    "id": "med-70",
    "topic": "Erros Clássicos de Exame",
    "title": "Radon–Nikodym: direção de $\\ll$",
    "hard": false,
    "byRuan": false,
    "ref": "§8",
    "prompt": "\"$\\nu \\ll \\mu$ significa $d\\nu/d\\mu$ existe.\" Essa densidade está em $L^1(\\mu)$ ou $L^1(\\nu)$?",
    "answer": "Se $\\nu(E) = \\int_E f \\, d\\mu$, prove que $\\int h \\, d\\nu = \\int hf \\, d\\mu$ para $h \\ge 0$ mensurável. Qual é a generalização (chain rule para derivadas de R-N)?"
  },
  {
    "id": "med-71",
    "topic": "Erros Clássicos de Exame",
    "title": "condição de dominação no DCT: versão exame",
    "hard": false,
    "byRuan": false,
    "ref": "§5",
    "prompt": "\"$f_n \\to f$ a.e. e $|f_n(x)| \\le n$.\" O DCT se aplica em $[0,1]$ com medida de Lebesgue?",
    "answer": "Não — o DCT padrão **não** se aplica: $|f_n| \\le n$ não é dominante uniforme em $n$ (o bound depende de $n$). Duas saídas possíveis: (1) se adicionalmente soubermos que $|f_n| \\le M$ para alguma constante $M$ independente de $n$, aplica-se o **Bounded Convergence Theorem** (medida finita + bound uniforme + convergência a.e. ⇒ $\\int f_n \\to \\int f$); (2) se a sequência for **uniformemente integrável** (critério de Vitali), aplica-se o Teorema de Vitali. Sem hipótese adicional, a troca não está garantida."
  },
  {
    "id": "med-72",
    "topic": "Erros Clássicos de Exame",
    "title": "integral e limite: questão-tipo de exame",
    "hard": false,
    "byRuan": false,
    "ref": "§5",
    "prompt": "Calcule $\\lim_{n \\to \\infty} \\int_0^\\infty \\frac{n}{1 + n^2 x^2} e^{-x} \\, dx$. Identifique o teorema que justifica cada passo.",
    "answer": "$f_n(x) = \\frac{n}{1+n^2x^2} e^{-x}$, $f_n \\to 0$ para $x > 0$. A dominante $g(x) = \\frac{1}{x} e^{-x}$ não está em $L^1$ perto de 0. Avalie a integral diretamente por substituição e compare com o limite formal."
  },
  {
    "id": "otim-1",
    "topic": "Espaços Afins (Vincent §1)",
    "title": "conjunto afim",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §1",
    "prompt": "Defina conjunto afim em $\\mathbb{R}^n$. Como se relaciona com subespaço vetorial?",
    "answer": "Todo subespaço vetorial é afim, mas nem todo conjunto afim é subespaço. Quando um conjunto afim é subespaço? Dê exemplo de conjunto afim que não passa pela origem."
  },
  {
    "id": "otim-2",
    "topic": "Espaços Afins (Vincent §1)",
    "title": "hull afim e dimensão afim",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §1",
    "prompt": "Defina combinação afim e hull afim ($\\text{aff}(C)$) de um conjunto $C$. O que é a dimensão afim de $C$?",
    "answer": "Calcule $\\text{aff}(\\{(1,0,0),(0,1,0),(0,0,1)\\})$ em $\\mathbb{R}^3$. Qual é a dimensão afim? Como se relaciona com o espaço solução de sistemas lineares?"
  },
  {
    "id": "otim-3",
    "topic": "Espaços Afins (Vincent §1)",
    "title": "interior relativo",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §1",
    "prompt": "Defina interior relativo $\\text{ri}(C)$ de um conjunto convexo $C$. Em qual espaço afim se toma o interior?",
    "answer": "O interior relativo de um segmento $[a,b]$ em $\\mathbb{R}^2$ é o interior no sentido usual? Calcule $\\text{ri}([a,b])$. Quando $\\text{ri}(C) = \\emptyset$?"
  },
  {
    "id": "otim-4",
    "topic": "Conjuntos Convexos (Vincent §2)",
    "title": "convexidade: definição",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §2",
    "prompt": "Defina conjunto convexo. Dê quatro exemplos em $\\mathbb{R}^n$ e dois não-exemplos.",
    "answer": "A interseção de conjuntos convexos é convexa? E a união? Prove a afirmação verdadeira e dê contraexemplo para a falsa."
  },
  {
    "id": "otim-5",
    "topic": "Conjuntos Convexos (Vincent §2)",
    "title": "hull convexo",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §2",
    "prompt": "Defina $\\text{conv}(C)$ (hull convexo). Enuncie sua caracterização como menor conjunto convexo contendo $C$.",
    "answer": "Qual é $\\text{conv}(\\{e_1, e_2, e_3\\})$ em $\\mathbb{R}^3$ (vértices do simplex)? E $\\text{conv}(S^{n-1})$ (esfera unitária)?"
  },
  {
    "id": "otim-6",
    "topic": "Conjuntos Convexos (Vincent §2)",
    "title": "separação e suporte",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §2",
    "prompt": "Enuncie o Teorema de Separação (dois conjuntos convexos disjuntos fechados podem ser separados por hiperplano). Qual hipótese é necessária se um deles não for fechado?",
    "answer": "Use separação para provar: se $x \\notin C$ (convexo fechado), existe hiperplano separando $x$ de $C$. Qual é a interpretação geométrica em termos de distância?"
  },
  {
    "id": "otim-7",
    "topic": "Conjuntos Convexos (Vincent §2)",
    "title": "operações que preservam convexidade",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §2",
    "prompt": "Quais operações preservam convexidade? Liste pelo menos cinco (interseção, imagem linear, preimagem, soma de Minkowski, etc.).",
    "answer": "O conjunto $\\{x : f(x) \\le c\\}$ (sublevel set) é convexo quando? E o conjunto $\\{(x,t): f(x) \\le t\\}$ (epígrafo)?"
  },
  {
    "id": "otim-8",
    "topic": "Cones (Vincent §3)",
    "title": "cone: definição",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §3",
    "prompt": "Defina cone em $\\mathbb{R}^n$ (com e sem a convenção de vértice na origem). O que é cone convexo?",
    "answer": "$\\{(x,y) : x \\ge 0, y \\ge 0\\}$ é cone convexo? $\\{(x,y): y = x^2\\}$ é cone? Justifique."
  },
  {
    "id": "otim-9",
    "topic": "Cones (Vincent §3)",
    "title": "cone dual",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §3",
    "prompt": "Defina o cone dual $C^* = \\{y : \\langle y, x \\rangle \\ge 0 \\, \\forall x \\in C\\}$. Qual é o dual do cone não-negativo $\\mathbb{R}^n_+$?",
    "answer": "Prove: $(C^*)^* \\supset \\overline{\\text{conv}}(C)$, com igualdade se $C$ é cone convexo fechado. Qual teorema garante a igualdade?"
  },
  {
    "id": "otim-10",
    "topic": "Cones (Vincent §3)",
    "title": "cone normal e cone tangente",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §3",
    "prompt": "Para $C$ convexo e $x \\in C$, defina cone normal $N_C(x)$ e cone tangente $T_C(x)$. Qual é a relação entre eles?",
    "answer": "Para $C = \\mathbb{R}^n_+$ e $x = (1, 0, 0, \\ldots, 0)$, compute $N_C(x)$ e $T_C(x)$ explicitamente."
  },
  {
    "id": "otim-11",
    "topic": "Cones (Vincent §3)",
    "title": "cone de segunda ordem (Lorentz)",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §3, Algorithms §4",
    "prompt": "Defina o cone de segunda ordem (ou cone de Lorentz / ice cream cone) $\\mathcal{L}^{n+1} = \\{(x,t) \\in \\mathbb{R}^{n+1} : \\|x\\| \\le t\\}$. Prove que é cone convexo.",
    "answer": "O que é $(\\mathcal{L}^{n+1})^*$? (É o próprio cone — mostre que o cone de Lorentz é self-dual.) Qual conexão com programação cônica quadrática?"
  },
  {
    "id": "otim-12",
    "topic": "Funções Convexas (Vincent §4)",
    "title": "convexidade: definição via Jensen",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "$f: C \\to \\mathbb{R}$ é convexa se e somente se... Escreva a definição via desigualdade de Jensen generalizada.",
    "answer": "Prove que $f(x) = \\|x\\|^2$ é convexa em $\\mathbb{R}^n$. Depois prove que $f(x) = \\|x\\|$ é convexa mas não estritamente convexa."
  },
  {
    "id": "otim-13",
    "topic": "Funções Convexas (Vincent §4)",
    "title": "epígrafo e convexidade",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "Enuncie a equivalência: $f$ é convexa $\\Leftrightarrow$ $\\text{epi}(f)$ é convexo. O que é $\\text{epi}(f)$?",
    "answer": "Prove que $f: \\mathbb{R}^n \\to \\mathbb{R}$ convexa implica os conjuntos de nível $\\{x: f(x) \\le c\\}$ são convexos. A recíproca vale?"
  },
  {
    "id": "otim-14",
    "topic": "Funções Convexas (Vincent §4)",
    "title": "funções fortemente convexas",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "Defina $f$ $\\sigma$-fortemente convexa ($\\sigma > 0$). Como isso se compara à convexidade usual? Dê dois exemplos.",
    "answer": "$f$ é $\\sigma$-fort. convexa $\\Rightarrow$ tem minimizador único. Prove essa implicação."
  },
  {
    "id": "otim-15",
    "topic": "Funções Convexas (Vincent §4)",
    "title": "subdiferencial",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "Defina subdiferencial $\\partial f(x)$ e subgradiente de $f$ convexo em $x$. Quando $\\partial f(x) = \\{f'(x)\\}$?",
    "answer": "Calcule $\\partial \\|\\cdot\\|_1$ em $x = (1, 0, -1)^T$. Quais são os subgradientes no ponto não-diferenciável?"
  },
  {
    "id": "otim-16",
    "topic": "Funções Convexas (Vincent §4)",
    "title": "operações que preservam convexidade de funções",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "Mostre que: (a) soma positiva de funções convexas é convexa; (b) composição $f \\circ A$ com mapa afim $A$ é convexa; (c) $\\sup_\\alpha f_\\alpha$ de funções convexas é convexa.",
    "answer": "$f(x) = \\max(0, x)$ (ReLU) é convexa? $f(x) = \\min(x^2, 1)$ é convexa? Justifique usando as regras acima."
  },
  {
    "id": "otim-17",
    "topic": "Funções Convexas (Vincent §4)",
    "title": "funções convexas e diferenciabilidade",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "Se $f$ é convexa e diferenciável, enuncie as condições de primeira e segunda ordem que caracterizam convexidade.",
    "answer": "$f: \\mathbb{R}^n \\to \\mathbb{R}$ convexa diferenciável. Prove: $f(y) \\ge f(x) + \\nabla f(x)^T (y-x)$ para todo $x,y$."
  },
  {
    "id": "otim-18",
    "topic": "Funções Convexas (Vincent §4)",
    "title": "função conjugada (Legendre–Fenchel)",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4, §7",
    "prompt": "Defina a conjugada de Fenchel $f^*(y) = \\sup_x \\{\\langle y, x \\rangle - f(x)\\}$. Prove que $f^*$ é sempre convexa (mesmo se $f$ não é).",
    "answer": "Calcule $f^*$ para $f(x) = \\frac{1}{2}\\|x\\|^2$ em $\\mathbb{R}^n$. Qual é a interpretação geométrica de $f^*$?"
  },
  {
    "id": "otim-19",
    "topic": "Funções Convexas (Vincent §4)",
    "title": "função de suporte",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "Defina a função de suporte $\\sigma_C(y) = \\sup_{x \\in C} \\langle y, x \\rangle$ de um conjunto $C$. Qual é a relação com a conjugada de $\\mathbf{1}_C$ (indicadora)?",
    "answer": "Compute $\\sigma_C$ para $C = B(0,1)$ (bola unitária em norma 2). E para $C = \\Delta_n$ (simplex de probabilidade)?"
  },
  {
    "id": "otim-20",
    "topic": "Operadores Não-Expansivos (Vincent §5)",
    "title": "operador não-expansivo",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §5",
    "prompt": "Defina operador não-expansivo $T: \\mathcal{H} \\to \\mathcal{H}$ em espaço de Hilbert. Defina $\\alpha$-averaged. Qual é a relação com operadores firmemente não-expansivos?",
    "answer": "A projeção ortogonal $P_C$ sobre convexo fechado $C$ é firmemente não-expansiva? Prove que é não-expansiva via desigualdade de Pytágoras generalizada."
  },
  {
    "id": "otim-21",
    "topic": "Operadores Não-Expansivos (Vincent §5)",
    "title": "operador proximal",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §5",
    "prompt": "Defina o operador proximal $\\text{prox}_{\\lambda f}(x) = \\arg\\min_y \\{f(y) + \\frac{1}{2\\lambda}\\|y - x\\|^2\\}$. Para $f = \\mathbf{1}_C$, o que é $\\text{prox}_{\\lambda f}$?",
    "answer": "Compute $\\text{prox}_{\\lambda \\|\\cdot\\|_1}(x)$ em $\\mathbb{R}$ (operador de soft-thresholding). Qual é a fórmula explícita?"
  },
  {
    "id": "otim-22",
    "topic": "Condições de Otimalidade (Vincent §6, Algorithms §6)",
    "title": "condições de primeira ordem para irrestrito",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §6, Algorithms §6",
    "prompt": "$f: \\mathbb{R}^n \\to \\mathbb{R}$ diferenciável, $x^*$ mínimo local. Condição necessária de 1ª ordem? Condição suficiente?",
    "answer": "Se $f$ é convexa, $\\nabla f(x^*) = 0$ é condição necessária e suficiente para mínimo *global*. Prove."
  },
  {
    "id": "otim-23",
    "topic": "Condições de Otimalidade (Vincent §6, Algorithms §6)",
    "title": "condições de segunda ordem",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §6",
    "prompt": "$f$ diferenciável duas vezes em $x^*$. Condições necessárias e suficientes de 2ª ordem para mínimo local.",
    "answer": "Por que a condição suficiente requer $\\nabla^2 f(x^*)$ *positivo definido* (não semidefinido)? Dê exemplo onde $\\nabla^2 f(0) \\succeq 0$ e $\\nabla f(0) = 0$ mas 0 não é mínimo."
  },
  {
    "id": "otim-24",
    "topic": "Condições de Otimalidade (Vincent §6, Algorithms §6)",
    "title": "KKT: enunciado completo",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6 (p.23–30)",
    "prompt": "Enuncie as condições KKT para o problema $\\min f(x)$ s.a. $g_i(x) \\le 0$, $h_j(x) = 0$. Quais são as quatro condições? (Primalidade, dualidade, complementaridade, estacionariedade.)",
    "answer": "KKT são condições necessárias sob qual qualificação de restrições (constraint qualification)? Liste pelo menos duas (Slater, LICQ). Qual é mais fácil de verificar na prática?"
  },
  {
    "id": "otim-25",
    "topic": "Condições de Otimalidade (Vincent §6, Algorithms §6)",
    "title": "KKT: complementaridade",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6",
    "prompt": "A condição de complementaridade diz $\\lambda_i g_i(x^*) = 0$ para todo $i$. O que significa economicamente / geometricamente?",
    "answer": "Em um problema de programação linear com restrição $x \\ge 0$, o que a complementaridade diz sobre variáveis básicas vs não-básicas na solução ótima?"
  },
  {
    "id": "otim-26",
    "topic": "Condições de Otimalidade (Vincent §6, Algorithms §6)",
    "title": "KKT: exemplo concreto",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6",
    "prompt": "Resolva via KKT: $\\min x^2 + y^2$ s.a. $x + y = 1$. Escreva o Lagrangiano, derive as condições KKT, resolva.",
    "answer": "Agora resolva $\\min x^2 + y^2$ s.a. $x + y \\ge 1$, $x,y \\ge 0$. Identifique restrições ativas na solução. O que a complementaridade diz?"
  },
  {
    "id": "otim-27",
    "topic": "Condições de Otimalidade (Vincent §6, Algorithms §6)",
    "title": "Lagrangiano e Lagrangiano dual",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §7, Algorithms §6",
    "prompt": "Para $\\min f(x)$ s.a. $g(x) \\le 0$, $h(x) = 0$: defina o Lagrangiano $L(x, \\lambda, \\nu)$. Defina a função dual $d(\\lambda, \\nu) = \\inf_x L(x,\\lambda,\\nu)$. Qual é sempre a relação entre $d(\\lambda,\\nu)$ e o valor ótimo primal?",
    "answer": "Prove a weak duality: $d(\\lambda, \\nu) \\le p^*$ para todo $\\lambda \\ge 0$. Qual hipótese garante strong duality ($d^* = p^*$)?"
  },
  {
    "id": "otim-28",
    "topic": "Dualidade (Vincent §7, Algorithms §2)",
    "title": "dualidade fraca e forte",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §7, Algorithms §2 (p.5–6)",
    "prompt": "Enuncie weak duality e strong duality. Qual é o gap de dualidade? Quando o gap é zero?",
    "answer": "Para PL (programação linear), strong duality sempre vale (quando o primal é factível e ilimitado não). Para QP (programação quadrática convexa), quando vale? O que pode falhar?"
  },
  {
    "id": "otim-29",
    "topic": "Dualidade (Vincent §7, Algorithms §2)",
    "title": "condição de Slater",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §7",
    "prompt": "Enuncie a condição de Slater para strong duality em programação convexa. O que é ponto estritamente factível?",
    "answer": "Dê exemplo de problema convexo sem ponto de Slater onde o gap de dualidade é estritamente positivo."
  },
  {
    "id": "otim-30",
    "topic": "Dualidade (Vincent §7, Algorithms §2)",
    "title": "dual do PL",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §2 (p.2–6)",
    "prompt": "Escreva o problema dual de $\\min c^T x$ s.a. $Ax = b$, $x \\ge 0$. Identifique as variáveis duais e a função objetivo dual.",
    "answer": "Interprete as variáveis duais como preços sombra. Se a restrição $i$ do primal é ativa, o que a complementaridade diz sobre o preço sombra $\\lambda_i$?"
  },
  {
    "id": "otim-31",
    "topic": "Dualidade (Vincent §7, Algorithms §2)",
    "title": "dual de problema de minimização geral",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §7",
    "prompt": "Para $\\min f(x)$ s.a. $g_i(x) \\le 0$: escreva o dual de Lagrange. Quando a função dual é diferenciável e qual é o seu gradiente?",
    "answer": "Para $f, g_i$ convexas e condição de Slater, mostre que o mínimo primal coincide com o máximo dual. Qual é o papel do ponto de sela do Lagrangiano?"
  },
  {
    "id": "otim-32",
    "topic": "Dualidade (Vincent §7, Algorithms §2)",
    "title": "conjugada de Fenchel e dualidade",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §7",
    "prompt": "Mostre que $f^{**} \\le f$ (bipolar), com igualdade se $f$ é convexa, própria, semicontínua inferiormente. Qual a conexão com dualidade de Fenchel–Rockafellar?",
    "answer": "Para $\\min f(x) + g(Ax)$, escreva o dual de Fenchel–Rockafellar. Quando vale strong duality?"
  },
  {
    "id": "otim-33",
    "topic": "Programação Linear (Algorithms §2)",
    "title": "LP: formas equivalentes",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §2",
    "prompt": "Escreva o PL padrão, o PL de forma canônica e prove que são equivalentes. O que são variáveis de folga?",
    "answer": "Converta $\\min c^T x$ s.a. $Ax \\le b$, $x \\in \\mathbb{R}^n$ para forma padrão $\\min c^T x$ s.a. $Ax = b$, $x \\ge 0$."
  },
  {
    "id": "otim-34",
    "topic": "Programação Linear (Algorithms §2)",
    "title": "vértices do poliedro e soluções básicas factíveis",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §2",
    "prompt": "Defina solução básica factível (BFS) de um PL. Prove que toda solução ótima de PL (se existe) pode ser tomada como BFS.",
    "answer": "Para o poliedro $\\{x \\ge 0: Ax = b\\}$ com $A \\in \\mathbb{R}^{m \\times n}$, $m < n$: qual é o número máximo de BFS? Como o método simplex se move entre elas?"
  },
  {
    "id": "otim-35",
    "topic": "Programação Linear (Algorithms §2)",
    "title": "simplex: conceito",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §2",
    "prompt": "Descreva o método simplex em linguagem de álgebra linear: o que é uma iteração, o que é a regra de pivô, por que converge (genericamente)?",
    "answer": "O simplex pode ciclrar? Qual regra de pivô garante terminação finita? (Regra de Bland.) Qual a complexidade de pior caso vs caso médio?"
  },
  {
    "id": "otim-36",
    "topic": "Programação Cônica (Algorithms §3–5)",
    "title": "programação cônica: forma geral",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §3",
    "prompt": "Escreva a forma geral de um problema de programação cônica (CP). Dê três exemplos de cones que se encaixam nessa forma: $\\mathbb{R}^n_+$, $\\mathcal{L}^{n+1}$, $\\mathcal{S}^n_+$.",
    "answer": "Por que a programação cônica unifica PL, SOCP, e SDP? Qual é o papel do cone dual na formulação do dual?"
  },
  {
    "id": "otim-37",
    "topic": "Programação Cônica (Algorithms §3–5)",
    "title": "SDP: motivação e forma",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §5",
    "prompt": "Escreva um SDP na forma padrão: $\\min \\text{tr}(CX)$ s.a. $\\text{tr}(A_i X) = b_i$, $X \\succeq 0$. O que significa $X \\succeq 0$?",
    "answer": "Mostre que todo PL é SDP (com $X$ diagonal). E todo SOCP? Esboce a embedding."
  },
  {
    "id": "otim-38",
    "topic": "Programação Cônica (Algorithms §3–5)",
    "title": "SOCP: forma e exemplos",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §4",
    "prompt": "Escreva um SOCP na forma padrão. Cite dois problemas aplicados que se reduzem a SOCP.",
    "answer": "O problema de mínima norma 2 sujeito a $Ax = b$ é SOCP ou LP? Formule como SOCP explicitamente."
  },
  {
    "id": "otim-39",
    "topic": "Condições de Otimalidade (Algorithms §6 — peso máximo)",
    "title": "KKT para problema convexo: interpretação",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6",
    "prompt": "Para $\\min f(x)$ s.a. $g_i(x) \\le 0$ com $f, g_i$ convexas e condição de Slater: as condições KKT são necessárias e suficientes. Prove suficiência.",
    "answer": "Para necessidade (sem convexidade), qual qualificação de restrições é usada? Quando LICQ vale versus quando Slater é mais adequado?"
  },
  {
    "id": "otim-40",
    "topic": "Condições de Otimalidade (Algorithms §6 — peso máximo)",
    "title": "KKT: multiplicadores não-negativos",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6",
    "prompt": "Por que $\\lambda_i \\ge 0$ para restrições de desigualdade e $\\nu_j$ livre para restrições de igualdade? Intuição geométrica.",
    "answer": "Se invertermos o sinal de $\\lambda_i$ (tomarmos $\\lambda_i \\le 0$), o que muda no argumento de necessidade? Qual é a relação com o cone normal à região factível?"
  },
  {
    "id": "otim-41",
    "topic": "Condições de Otimalidade (Algorithms §6 — peso máximo)",
    "title": "KKT: sensitivity analysis",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6",
    "prompt": "O multiplicador $\\lambda_i$ mede a sensibilidade do valor ótimo ao perturbador $b_i$ em $g_i(x) \\le b_i$. Formalize: qual é $\\partial p^* / \\partial b_i$?",
    "answer": "Em um problema de planejamento de produção, a restrição é de capacidade. O que o multiplicador KKT diz sobre o valor marginal de aumentar a capacidade?"
  },
  {
    "id": "otim-42",
    "topic": "Condições de Otimalidade (Algorithms §6 — peso máximo)",
    "title": "Fritz John vs KKT",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6",
    "prompt": "As condições de Fritz John são condições necessárias sem qualificação de restrições. Como diferem de KKT? O que pode degenerar nas condições de Fritz John?",
    "answer": "Dê exemplo de problema onde Fritz John é satisfeita com $\\mu_0 = 0$ (ponto anormal). Por que isso é problemático para dualidade?"
  },
  {
    "id": "otim-43",
    "topic": "Robust Programming (Algorithms §7)",
    "title": "otimização robusta: motivação",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §7 (p.30–38)",
    "prompt": "O que é programação robusta? Como se formula $\\min_x \\max_{u \\in \\mathcal{U}} f(x, u)$ s.a. $g(x, u) \\le 0$ para todo $u \\in \\mathcal{U}$?",
    "answer": "Para $\\mathcal{U}$ elipsoidal, mostre que a restrição robusta $a^T x \\le b$ para todo $a \\in \\mathcal{U} = \\{\\bar{a} + Pu: \\|u\\| \\le 1\\}$ equivale a uma restrição SOCP."
  },
  {
    "id": "otim-44",
    "topic": "Robust Programming (Algorithms §7)",
    "title": "robust LP com incerteza no custo",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §7",
    "prompt": "$\\min_{x \\ge 0} \\max_{c \\in \\mathcal{U}} c^T x$ s.a. $Ax \\le b$. Para $\\mathcal{U} = \\{c: \\|c - \\bar{c}\\| \\le \\rho\\}$, reformule como problema tratável.",
    "answer": "A reformulação usa a conjugada da norma: $\\max_{c: \\|c - \\bar{c}\\| \\le \\rho} c^T x = \\bar{c}^T x + \\rho \\|x\\|_*$. Derive isso a partir da desigualdade de Cauchy–Schwarz."
  },
  {
    "id": "otim-45",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "gradiente descendente: convergência",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8 (p.38–42)",
    "prompt": "Enuncie o teorema de convergência do gradiente descendente para $f$ convexa e $L$-suave (Lipschitz gradient). Taxa de convergência no valor objetivo?",
    "answer": "Para $f$ $\\mu$-fort. convexa e $L$-suave: qual é a taxa linear de convergência? O que é o número de condição $\\kappa = L/\\mu$?"
  },
  {
    "id": "otim-46",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "gradiente projetado",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8 (p.42–43)",
    "prompt": "Para $\\min_{x \\in C} f(x)$ com $C$ convexo fechado: descreva um passo do gradiente projetado. Por que a projeção $P_C$ aparece?",
    "answer": "O gradiente projetado com step-size constante converge para o mínimo se... (condição em $f$ e no step-size). Prove a desigualdade de descida para um passo."
  },
  {
    "id": "otim-47",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "método proximal",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8",
    "prompt": "O passo proximal $x^{k+1} = \\text{prox}_{\\lambda f}(x^k)$ resolve $\\min f$ sem projeção. Por que é útil quando $f$ é não-suave?",
    "answer": "Mostre que para $f = \\mathbf{1}_C$, o método proximal coincide com projeção. E para $f = \\|\\cdot\\|_1$, qual é o operador proximal?"
  },
  {
    "id": "otim-48",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "gradiente conjugado",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8 (p.43–44)",
    "prompt": "Para quadráticas $\\min \\frac{1}{2}x^T A x - b^T x$ com $A \\succ 0$: o gradiente conjugado (CG) converge em exatamente quantas iterações em $\\mathbb{R}^n$? Qual é a taxa em termos de $\\kappa(A)$?",
    "answer": "CG é um método de Krylov. Explique o que significa \"explorar o subespaço de Krylov\" e por que isso é melhor que gradiente descendente."
  },
  {
    "id": "otim-49",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "Método de Newton",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8 (p.44–45)",
    "prompt": "Descreva um passo do método de Newton. Condição de convergência (local/global). Taxa de convergência quadrática: o que significa?",
    "answer": "Newton usa $\\nabla^2 f$ — caro quando $n$ grande. Quais são as alternativas quasi-Newton? Cite dois métodos (BFGS, L-BFGS) e sua taxa de convergência."
  },
  {
    "id": "otim-50",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "Douglas–Rachford e ADMM",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8 (p.46–48)",
    "prompt": "Para $\\min f(x) + g(x)$, o splitting Douglas–Rachford alterna projeções/proximais em $f$ e $g$. Qual é a sequência de iterações?",
    "answer": "Como o ADMM (Augmented Lagrangian Method with Decomposition) se relaciona com Douglas–Rachford? Qual é o papel do parâmetro de penalidade $\\rho$?"
  },
  {
    "id": "otim-51",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "Lagrangiano aumentado",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8 (p.48–49)",
    "prompt": "Defina o Lagrangiano aumentado para $\\min f(x)$ s.a. $Ax = b$: $L_\\rho(x,\\lambda) = f(x) + \\lambda^T(Ax - b) + \\frac{\\rho}{2}\\|Ax - b\\|^2$. Por que o termo quadrático ajuda?",
    "answer": "O método do multiplicador (ALM) atualiza $\\lambda^{k+1} = \\lambda^k + \\rho(Ax^k - b)$. Prove que no mínimo exato com $\\rho$ suficientemente grande, o gradiente se anula."
  },
  {
    "id": "otim-52",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "geração de colunas",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8 (p.49–50)",
    "prompt": "Descreva o princípio da geração de colunas para PL com muitas variáveis. O que é o \"pricing problem\"?",
    "answer": "Por que geração de colunas é relevante para SDDP? A relação com relaxação Lagrangiana: qual é o pricing problem em programação estocástica?"
  },
  {
    "id": "otim-53",
    "topic": "Algoritmos de Primeira Ordem (Algorithms §8)",
    "title": "método bundle",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8 (p.50–51)",
    "prompt": "Para $f$ convexa não-suave: o método bundle acumula subgradientes passados para construir um modelo por partes. Como ele decide a direção de descida?",
    "answer": "Qual é a relação entre bundle methods e a solução do problema dual via subgradiente? Por que bundle converge onde subgradiente puro oscila?"
  },
  {
    "id": "otim-54",
    "topic": "Conexões com PhD (SDDP/SOC)",
    "title": "SDDP e dualidade",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §8, sua dissertação",
    "prompt": "O SDDP (Stochastic Dual Dynamic Programming) resolve $\\min \\mathbb{E}[c^T x + Q(x,\\xi)]$ via cortes de Benders. Qual é a conexão com o algoritmo de geração de colunas e com bundle methods?",
    "answer": "Os cortes de Benders são planos de suporte à função de valor $Q$. Em linguagem de Convex Analysis, o que é $Q$ e qual é o paper que mostra sua convexidade?"
  },
  {
    "id": "otim-55",
    "topic": "Conexões com PhD (SDDP/SOC)",
    "title": "relaxação Lagrangiana em SOC",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6–8",
    "prompt": "Para um problema com restrições acoplantes $h(x,y) = 0$, a relaxação Lagrangiana descola o acoplamento. Escreva o dual e identifique o subproblema.",
    "answer": "O gap de dualidade na relaxação Lagrangiana é zero quando? Qual condição (convexidade, CQ) é suficiente?"
  },
  {
    "id": "otim-56",
    "topic": "Erros Clássicos de Exame",
    "title": "KKT sem qualificação de restrições",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6",
    "prompt": "\"Todo ponto ótimo satisfaz as condições KKT.\" Correto?",
    "answer": "Não sem qualificação de restrições. Dê exemplo de $\\min f(x)$ s.a. $g(x) \\le 0$ onde o ótimo não satisfaz KKT porque a CQ falha. (Dica: $g(x) = (x-1)^3$, $\\min x$.)"
  },
  {
    "id": "otim-57",
    "topic": "Erros Clássicos de Exame",
    "title": "strong duality automática",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §7",
    "prompt": "\"O problema é convexo, portanto strong duality vale.\" Correto?",
    "answer": "Precisa de condição de qualificação (e.g., Slater). Dê exemplo convexo onde o gap de dualidade é positivo porque Slater falha."
  },
  {
    "id": "otim-58",
    "topic": "Erros Clássicos de Exame",
    "title": "complementaridade: ambas as direções",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6",
    "prompt": "KKT diz $\\lambda_i g_i(x^*) = 0$. Isso significa $\\lambda_i = 0$ **ou** $g_i = 0$. Pode ambos serem zero?",
    "answer": "Sim — isso é degeneração (complementaridade degenerada). Quais consequências para sensitivity analysis e para unicidade dos multiplicadores?"
  },
  {
    "id": "otim-59",
    "topic": "Erros Clássicos de Exame",
    "title": "convexidade estrita vs forte",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "Defina convexidade estrita e forte. Qual implica a outra? Dê exemplo separando as duas noções.",
    "answer": "$f(x) = x^4$ em $\\mathbb{R}$: é estritamente convexa? É fortemente convexa? Calcule $f''$ e identifique onde a forte convexidade falha."
  },
  {
    "id": "otim-60",
    "topic": "Erros Clássicos de Exame",
    "title": "mínimo local vs global em problema convexo",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §6",
    "prompt": "\"Para problema de otimização convexo, todo mínimo local é global.\" Prove.",
    "answer": "A prova usa apenas a definição de convexidade do conjunto factível e da função objetivo. Escreva o argumento em três linhas. Qual hipótese (convexidade do factível ou do objetivo) é mais crítica?"
  },
  {
    "id": "otim-61",
    "topic": "Erros Clássicos de Exame",
    "title": "a condição de Slater em prática",
    "hard": false,
    "byRuan": false,
    "ref": "Algorithms §6, Convex Analysis §7",
    "prompt": "Para $\\min x_1^2 + x_2^2$ s.a. $x_1 + x_2 \\ge 1$, $x_1, x_2 \\ge 0$: encontre um ponto de Slater. Depois verifique as condições KKT na solução ótima.",
    "answer": "Solução ótima $(1/2, 1/2)$. Multiplique as restrições e verifique complementaridade. Quais restrições são ativas?"
  },
  {
    "id": "otim-62",
    "topic": "Revisão Rápida (Cards de definição pura)",
    "title": "vocabulário: convex hull, affine hull, cone hull",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §1–3",
    "prompt": "Defina $\\text{conv}(C)$, $\\text{aff}(C)$, $\\text{cone}(C)$ em uma linha cada. Qual a relação de inclusão entre eles (em geral)?",
    "answer": "Para $C = \\{e_1, e_2, e_3\\}$ em $\\mathbb{R}^3$: calcule os três hulls."
  },
  {
    "id": "otim-63",
    "topic": "Revisão Rápida (Cards de definição pura)",
    "title": "função positivamente homogênea",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §2–4",
    "prompt": "Defina função positivamente homogênea de grau 1. Cite dois exemplos: norma e função de suporte. Prove que $\\sigma_C$ é positivamente homogênea.",
    "answer": "Toda norma é positivamente homogênea? E toda função de suporte é norma? Quando vale?"
  },
  {
    "id": "otim-64",
    "topic": "Revisão Rápida (Cards de definição pura)",
    "title": "projeção: unicidade e não-expansividade",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §5",
    "prompt": "Para $C$ convexo fechado em $\\mathbb{R}^n$, prove unicidade de $P_C(x) = \\arg\\min_{y \\in C} \\|y - x\\|$. Prove $\\|P_C(x) - P_C(y)\\| \\le \\|x - y\\|$.",
    "answer": "A projeção em conjunto não-convexo pode não existir ou não ser única. Dê exemplo de cada patologia."
  },
  {
    "id": "otim-65",
    "topic": "Revisão Rápida (Cards de definição pura)",
    "title": "level sets e funções convexas",
    "hard": false,
    "byRuan": false,
    "ref": "Convex Analysis §4",
    "prompt": "Os sublevel sets $\\{x: f(x) \\le \\alpha\\}$ de função convexa são convexos. A recíproca vale? Defina \"função quasi-convexa\".",
    "answer": "$f(x,y) = xy$ é quasi-convexa em $\\mathbb{R}^2$? Em $\\mathbb{R}^2_+$? Verifique a definição diretamente."
  }
];

window.DECKS = {
  "med": {
    "count": 72,
    "ids": [
      "med-1",
      "med-2",
      "med-3",
      "med-4",
      "med-5",
      "med-6",
      "med-7",
      "med-8",
      "med-9",
      "med-10",
      "med-11",
      "med-12",
      "med-13",
      "med-14",
      "med-15",
      "med-16",
      "med-17",
      "med-18",
      "med-19",
      "med-20",
      "med-21",
      "med-22",
      "med-23",
      "med-24",
      "med-25",
      "med-26",
      "med-27",
      "med-28",
      "med-29",
      "med-30",
      "med-31",
      "med-32",
      "med-33",
      "med-34",
      "med-35",
      "med-36",
      "med-37",
      "med-38",
      "med-39",
      "med-40",
      "med-41",
      "med-42",
      "med-43",
      "med-44",
      "med-45",
      "med-46",
      "med-47",
      "med-48",
      "med-49",
      "med-50",
      "med-51",
      "med-52",
      "med-53",
      "med-54",
      "med-55",
      "med-56",
      "med-57",
      "med-58",
      "med-59",
      "med-60",
      "med-61",
      "med-62",
      "med-63",
      "med-64",
      "med-65",
      "med-66",
      "med-67",
      "med-68",
      "med-69",
      "med-70",
      "med-71",
      "med-72"
    ]
  },
  "otim": {
    "count": 65,
    "ids": [
      "otim-1",
      "otim-2",
      "otim-3",
      "otim-4",
      "otim-5",
      "otim-6",
      "otim-7",
      "otim-8",
      "otim-9",
      "otim-10",
      "otim-11",
      "otim-12",
      "otim-13",
      "otim-14",
      "otim-15",
      "otim-16",
      "otim-17",
      "otim-18",
      "otim-19",
      "otim-20",
      "otim-21",
      "otim-22",
      "otim-23",
      "otim-24",
      "otim-25",
      "otim-26",
      "otim-27",
      "otim-28",
      "otim-29",
      "otim-30",
      "otim-31",
      "otim-32",
      "otim-33",
      "otim-34",
      "otim-35",
      "otim-36",
      "otim-37",
      "otim-38",
      "otim-39",
      "otim-40",
      "otim-41",
      "otim-42",
      "otim-43",
      "otim-44",
      "otim-45",
      "otim-46",
      "otim-47",
      "otim-48",
      "otim-49",
      "otim-50",
      "otim-51",
      "otim-52",
      "otim-53",
      "otim-54",
      "otim-55",
      "otim-56",
      "otim-57",
      "otim-58",
      "otim-59",
      "otim-60",
      "otim-61",
      "otim-62",
      "otim-63",
      "otim-64",
      "otim-65"
    ]
  }
};
