// Measure Theory Sparring — card deck.
// Each card: { id, topic, prompt (markdown w/ KaTeX), answer (markdown w/ KaTeX) }.
// Topic is a coarse tag for filtering; ids are stable so localStorage progress
// survives edits to wording.
window.CARDS = [
  // ─── σ-ALGEBRAS ────────────────────────────────────────────────────
  {
    id: "sa01", topic: "σ-algebras",
    prompt: "State the three axioms of a σ-algebra $\\mathcal{A}$ on a set $X$, and give one example that is **not** a σ-algebra.",
    answer:
      "<h4>Axioms</h4>" +
      "<p>(i) $\\emptyset \\in \\mathcal{A}$. " +
      "(ii) $A \\in \\mathcal{A} \\Rightarrow A^c \\in \\mathcal{A}$. " +
      "(iii) $\\{A_n\\}_{n\\ge 1} \\subset \\mathcal{A} \\Rightarrow \\bigcup_n A_n \\in \\mathcal{A}$.</h4>" +
      "<h4>Non-example</h4>" +
      "<p>The collection of all <em>finite</em> subsets of $\\mathbb{N}$ together with $\\emptyset$ and $\\mathbb{N}$ — closed under finite unions and complements <em>relative to itself</em>, but not under countable unions of singletons, since $\\bigcup_{n=1}^\\infty \\{2n\\} = 2\\mathbb{N}$ is infinite-and-coinfinite, so not in the collection.</p>" +
      "<h4>Trick</h4>" +
      "<p>Algebras (closed under finite ops) are easy; the σ in σ-algebra carries the weight. When asked to verify, the failing axiom is almost always (iii)."
  },
  {
    id: "sa02", topic: "σ-algebras",
    prompt: "Prove: the intersection of an arbitrary family of σ-algebras on $X$ is again a σ-algebra. State the consequence (generated σ-algebra).",
    answer:
      "<p>Let $\\{\\mathcal{A}_\\alpha\\}_{\\alpha \\in I}$ be σ-algebras on $X$ and $\\mathcal{A} := \\bigcap_\\alpha \\mathcal{A}_\\alpha$.</p>" +
      "<p>(i) Each $\\mathcal{A}_\\alpha$ contains $\\emptyset$, so $\\emptyset \\in \\mathcal{A}$. " +
      "(ii) If $A \\in \\mathcal{A}$, then $A \\in \\mathcal{A}_\\alpha$ for every $\\alpha$, hence $A^c \\in \\mathcal{A}_\\alpha$ for every $\\alpha$, hence $A^c \\in \\mathcal{A}$. " +
      "(iii) Same argument with countable unions.</p>" +
      "<h4>Consequence</h4>" +
      "<p>Given any $\\mathcal{C} \\subset 2^X$, the family of σ-algebras containing $\\mathcal{C}$ is non-empty (contains $2^X$) and its intersection is a σ-algebra — call it $\\sigma(\\mathcal{C})$, the σ-algebra <em>generated by</em> $\\mathcal{C}$. It is the smallest σ-algebra containing $\\mathcal{C}$.</p>" +
      "<h4>Trick</h4>" +
      "<p>Crucial: <em>unions</em> of σ-algebras need not be σ-algebras. Intersection is the well-behaved direction."
  },
  {
    id: "sa03", topic: "σ-algebras",
    prompt: "What is the **Borel σ-algebra** $\\mathcal{B}(\\mathbb{R})$? Give three different generating families and prove they all generate the same σ-algebra.",
    answer:
      "<p>$\\mathcal{B}(\\mathbb{R}) := \\sigma(\\text{open sets of } \\mathbb{R})$.</p>" +
      "<h4>Equivalent generators</h4>" +
      "<p>(a) Open sets. (b) Closed sets. (c) Open intervals $(a,b)$. (d) Half-lines $(a,\\infty)$. (e) Half-lines $(-\\infty,b]$.</p>" +
      "<h4>Why they coincide</h4>" +
      "<p>Each is contained in the σ-algebra generated by the others, so by minimality they all equal $\\mathcal{B}(\\mathbb{R})$. E.g. open intervals generate open sets because every open subset of $\\mathbb{R}$ is a countable union of open intervals (rational endpoints suffice). Half-lines $(a,\\infty)$ generate open intervals via $(a,b) = (a,\\infty) \\setminus [b,\\infty) = (a,\\infty) \\cap (b,\\infty)^c$.</p>" +
      "<h4>Trick</h4>" +
      "<p>To prove two σ-algebras agree, you only ever need: each one contains a generating family for the other."
  },

  // ─── MEASURABLE FUNCTIONS ──────────────────────────────────────────
  {
    id: "mf01", topic: "Measurable functions",
    prompt: "Give four equivalent characterizations of a measurable function $f:(X,\\mathcal{A})\\to(\\mathbb{R},\\mathcal{B})$.",
    answer:
      "<p>$f$ is measurable iff any one of these holds (and they are all equivalent):</p>" +
      "<p>(a) $f^{-1}(B) \\in \\mathcal{A}$ for every $B \\in \\mathcal{B}(\\mathbb{R})$.<br>" +
      "(b) $\\{f > a\\} := f^{-1}((a,\\infty)) \\in \\mathcal{A}$ for every $a \\in \\mathbb{R}$.<br>" +
      "(c) $\\{f \\ge a\\} \\in \\mathcal{A}$ for every $a \\in \\mathbb{R}$.<br>" +
      "(d) $f^{-1}(U) \\in \\mathcal{A}$ for every open $U \\subset \\mathbb{R}$.</p>" +
      "<h4>Why the trick works</h4>" +
      "<p>$\\{B \\subset \\mathbb{R} : f^{-1}(B) \\in \\mathcal{A}\\}$ is automatically a σ-algebra (preimages preserve set ops). So if it contains a <em>generating</em> family of $\\mathcal{B}(\\mathbb{R})$, it contains all of $\\mathcal{B}(\\mathbb{R})$. Half-lines suffice — that's why (b) is enough.</p>"
  },
  {
    id: "mf02", topic: "Measurable functions",
    prompt: "Prove: if $\\{f_n\\}$ is a sequence of measurable functions $X \\to \\mathbb{R}$, then $\\sup_n f_n$, $\\inf_n f_n$, $\\limsup f_n$, $\\liminf f_n$, and $\\lim f_n$ (where it exists) are all measurable.",
    answer:
      "<h4>$\\sup$ is measurable</h4>" +
      "<p>$\\{\\sup_n f_n > a\\} = \\bigcup_n \\{f_n > a\\}$. Countable union of measurable sets, so measurable. Hence $\\sup_n f_n$ is measurable.</p>" +
      "<h4>$\\inf$ is measurable</h4>" +
      "<p>$\\inf_n f_n = -\\sup_n (-f_n)$. Or: $\\{\\inf_n f_n < a\\} = \\bigcup_n \\{f_n < a\\}$.</p>" +
      "<h4>$\\limsup$, $\\liminf$ are measurable</h4>" +
      "<p>$\\limsup_n f_n = \\inf_k \\sup_{n \\ge k} f_n$, so it is built from countably many sup/inf, all measurable.</p>" +
      "<h4>Pointwise limit</h4>" +
      "<p>If $\\lim_n f_n$ exists everywhere (or a.e.), it equals $\\limsup_n f_n$, hence measurable.</p>" +
      "<h4>Trick</h4>" +
      "<p>Pointwise limits of measurable functions are measurable. <em>Pointwise limits of continuous functions need not be continuous.</em> Measurability is the closure under pointwise limits that continuity lacks — that's its core power."
  },
  {
    id: "mf03", topic: "Measurable functions",
    prompt: "$f: X \\to \\mathbb{R}$ is measurable, $g: \\mathbb{R} \\to \\mathbb{R}$ is continuous (or Borel). Is $g \\circ f$ measurable? Is $f \\circ g$? Be careful.",
    answer:
      "<h4>$g \\circ f$: yes</h4>" +
      "<p>Continuous $\\Rightarrow$ Borel. For $B \\in \\mathcal{B}(\\mathbb{R})$, $(g \\circ f)^{-1}(B) = f^{-1}(g^{-1}(B)) \\in \\mathcal{A}$ since $g^{-1}(B) \\in \\mathcal{B}(\\mathbb{R})$ and $f$ is measurable.</p>" +
      "<h4>$f \\circ g$: only as a function $\\mathbb{R} \\to \\mathbb{R}$, and even then needs care</h4>" +
      "<p>The composition only makes sense if $f$ has domain containing the range of $g$. The natural setup is different: $f \\circ g$ as a function on $\\mathbb{R}$ is measurable when $g$ is Borel measurable, regardless of $f$'s domain measurability — it's a different statement.</p>" +
      "<h4>Trick: Lebesgue-measurable + continuous breaks</h4>" +
      "<p>If $\\mathcal{A}$ is the <em>Lebesgue</em> σ-algebra (not Borel), and $g$ is continuous, $g \\circ f$ is still measurable. But the composition $f \\circ h$ where $h$ is continuous and $f$ is Lebesgue-measurable can <em>fail</em> to be Lebesgue-measurable. The classical example: Cantor's staircase $h$ maps a non-measurable set's preimage to a measurable set."
  },

  // ─── INTEGRATION / CONVERGENCE THEOREMS ────────────────────────────
  {
    id: "in01", topic: "Convergence theorems",
    prompt: "State the **Monotone Convergence Theorem** with all hypotheses, then prove it (sketch).",
    answer:
      "<h4>Statement</h4>" +
      "<p>Let $(X,\\mathcal{A},\\mu)$ be a measure space and $\\{f_n\\}$ a sequence of measurable functions $X \\to [0,\\infty]$ with $f_n \\nearrow f$ pointwise (a.e.). Then $\\int f_n \\, d\\mu \\nearrow \\int f \\, d\\mu$.</p>" +
      "<h4>Proof sketch</h4>" +
      "<p>The sequence $\\int f_n$ is monotone nondecreasing, so it has a limit $L \\le \\int f$. For the reverse: take a simple function $0 \\le \\varphi \\le f$ and $\\alpha \\in (0,1)$. Set $E_n := \\{f_n \\ge \\alpha \\varphi\\}$. Then $E_n \\nearrow X$ (since $\\alpha < 1$ and $f_n \\to f \\ge \\varphi$), so $\\int_{E_n} \\alpha \\varphi \\, d\\mu \\nearrow \\alpha \\int \\varphi \\, d\\mu$ by continuity of measure. Bound $\\int f_n \\ge \\int_{E_n} f_n \\ge \\alpha \\int_{E_n} \\varphi$, so $L \\ge \\alpha \\int \\varphi$. Sup over $\\alpha < 1$ and $\\varphi \\le f$ to get $L \\ge \\int f$.</p>" +
      "<h4>Hypotheses are sharp</h4>" +
      "<p>(a) Non-negativity needed. (b) Monotonicity needed. Drop either and you lose the conclusion."
  },
  {
    id: "in02", topic: "Convergence theorems",
    prompt: "State the **Dominated Convergence Theorem**. Where in the hypotheses is the trap most students miss?",
    answer:
      "<h4>Statement</h4>" +
      "<p>Let $\\{f_n\\}$ be measurable functions $X \\to \\mathbb{R}$ with $f_n \\to f$ pointwise (a.e.), and suppose there exists an <strong>integrable</strong> $g: X \\to [0,\\infty]$ (i.e. $\\int g \\, d\\mu < \\infty$) with $|f_n| \\le g$ a.e. for every $n$. Then $f$ is integrable and $\\int f_n \\, d\\mu \\to \\int f \\, d\\mu$. (Stronger: $\\int |f_n - f| \\to 0$.)</p>" +
      "<h4>Trap</h4>" +
      "<p>The dominating function $g$ must be <em>independent of $n$</em> AND <em>integrable</em>. A common error is finding a $g_n$ that dominates each $f_n$ separately — that's not enough. The other miss: $|f_n| \\le n$ is not a dominator unless $\\mu(X) < \\infty$.</p>" +
      "<h4>Counterexample (no dominator)</h4>" +
      "<p>$f_n = n \\cdot \\mathbf{1}_{[0,1/n]}$ on $\\mathbb{R}$ with Lebesgue measure. $f_n \\to 0$ pointwise. $\\int f_n = 1$ for all $n$. $\\int f_n \\not\\to \\int 0 = 0$. The smallest dominator is $\\sup_n f_n = \\infty \\cdot \\mathbf{1}_{\\{0\\}} \\cup \\frac{1}{x} \\mathbf{1}_{(0,1]}$ which is not integrable on $(0,1]$."
  },
  {
    id: "in03", topic: "Convergence theorems",
    prompt: "State **Fatou's Lemma**. Give a sequence where the inequality is strict.",
    answer:
      "<h4>Statement</h4>" +
      "<p>For measurable $f_n: X \\to [0,\\infty]$ (a.e.), $\\int \\liminf_n f_n \\, d\\mu \\le \\liminf_n \\int f_n \\, d\\mu$.</p>" +
      "<h4>Strict-inequality example</h4>" +
      "<p>$f_n = \\mathbf{1}_{[n,n+1]}$ on $\\mathbb{R}$. $\\liminf_n f_n = 0$ everywhere (every point is left behind), so LHS $= 0$. But $\\int f_n = 1$ for all $n$, so RHS $= 1$.</p>" +
      "<h4>Mnemonic</h4>" +
      "<p>Mass can <em>escape to infinity</em> (or to a set of measure zero) under $\\liminf$ — Fatou records that the integral can only lose mass, never gain it. The reverse inequality requires a dominator (DCT) or monotonicity (MCT) to plug the leak."
  },
  {
    id: "in04", topic: "Convergence theorems",
    prompt: "Drill: which theorem do you reach for? For each scenario, name MCT / DCT / Fatou / none, and justify.",
    answer:
      "<p><strong>Scenario A.</strong> $f_n(x) = n x^{n-1}$ on $[0,1]$, Lebesgue. <em>Pointwise limit 0 a.e.</em></p>" +
      "<p>None applies cleanly: $\\int f_n = 1$ for all $n$, but the dominator $\\sup_n f_n$ is unbounded near $x=1$ and not integrable. Conclusion via direct computation: $\\int f_n \\to 1 \\ne 0$.</p>" +
      "<p><strong>Scenario B.</strong> $f_n \\nearrow f$ measurable, all non-negative.</p>" +
      "<p>MCT. No dominator needed.</p>" +
      "<p><strong>Scenario C.</strong> $f_n \\to f$ pointwise on $[0,1]$, $|f_n| \\le 5$.</p>" +
      "<p>DCT with $g \\equiv 5$ on $[0,1]$ (finite measure $\\Rightarrow$ constant dominator works).</p>" +
      "<p><strong>Scenario D.</strong> $f_n$ measurable, $f_n \\ge 0$, no monotonicity, you only want a one-sided bound.</p>" +
      "<p>Fatou. Gives $\\int \\liminf f_n \\le \\liminf \\int f_n$ for free.</p>"
  },

  // ─── L^p SPACES ────────────────────────────────────────────────────
  {
    id: "lp01", topic: "Lp spaces",
    prompt: "State **Hölder's inequality** and **Minkowski's inequality**. What's the conjugate-exponent condition?",
    answer:
      "<h4>Hölder</h4>" +
      "<p>For $\\frac{1}{p} + \\frac{1}{q} = 1$ with $p,q \\in [1,\\infty]$ (conjugate exponents), $\\int |fg| \\, d\\mu \\le \\|f\\|_p \\|g\\|_q$.</p>" +
      "<h4>Minkowski</h4>" +
      "<p>For $p \\in [1,\\infty]$, $\\|f+g\\|_p \\le \\|f\\|_p + \\|g\\|_p$. (This is the triangle inequality that makes $\\|\\cdot\\|_p$ a norm.)</p>" +
      "<h4>Edge cases</h4>" +
      "<p>$p=1, q=\\infty$: $\\int |fg| \\le \\|f\\|_1 \\|g\\|_\\infty$. $p=q=2$: Cauchy–Schwarz.</p>" +
      "<h4>Why Minkowski is hard for $p \\in (1,\\infty)$</h4>" +
      "<p>The proof uses Hölder applied to $|f+g|^p = |f+g| \\cdot |f+g|^{p-1}$, splitting $|f+g| \\le |f| + |g|$ and using the conjugate $q = p/(p-1)$. The case $p=1$ is the pointwise triangle inequality; $p=\\infty$ is essential-sup."
  },
  {
    id: "lp02", topic: "Lp spaces",
    prompt: "Sketch the proof that $L^p$ is **complete** ($p \\in [1,\\infty)$).",
    answer:
      "<p>Let $\\{f_n\\}$ be Cauchy in $L^p$.</p>" +
      "<h4>Step 1 — extract a fast-convergent subsequence</h4>" +
      "<p>Pick $n_1 < n_2 < \\dots$ with $\\|f_{n_{k+1}} - f_{n_k}\\|_p < 2^{-k}$.</p>" +
      "<h4>Step 2 — build a dominator</h4>" +
      "<p>Let $g_K(x) := \\sum_{k=1}^K |f_{n_{k+1}}(x) - f_{n_k}(x)|$ and $g(x) := \\sum_{k=1}^\\infty |\\dots|$. By Minkowski, $\\|g_K\\|_p \\le \\sum_k 2^{-k} < 1$, so by MCT $\\|g\\|_p \\le 1$, hence $g$ is finite a.e.</p>" +
      "<h4>Step 3 — pointwise limit</h4>" +
      "<p>Since the series defining $g$ converges absolutely a.e., the telescoping series $f_{n_K} = f_{n_1} + \\sum_{k=1}^{K-1}(f_{n_{k+1}} - f_{n_k})$ converges to a limit $f$ a.e. Then $|f_{n_K} - f|^p \\le (2g)^p$, dominated, so DCT gives $\\|f_{n_K} - f\\|_p \\to 0$.</p>" +
      "<h4>Step 4 — full sequence</h4>" +
      "<p>Cauchy + a subsequence converging to $f$ implies the whole sequence converges to $f$.</p>" +
      "<h4>Trick</h4>" +
      "<p>The series-of-norms construction is the canonical move for completeness in normed function spaces. Memorize this template — it's not just for $L^p$."
  },
  {
    id: "lp03", topic: "Lp spaces",
    prompt: "On a finite measure space ($\\mu(X) < \\infty$), what are the inclusions among $L^p$ spaces? What if $\\mu(X) = \\infty$?",
    answer:
      "<h4>Finite measure: $L^p \\supset L^q$ for $p \\le q$.</h4>" +
      "<p>By Hölder applied to $|f|^p \\cdot 1$: $\\int |f|^p \\le (\\int |f|^q)^{p/q} \\mu(X)^{1-p/q} < \\infty$. So $L^\\infty \\subset L^q \\subset L^p \\subset L^1$.</p>" +
      "<h4>Infinite measure: no general inclusions</h4>" +
      "<p>$f(x) = 1/x$ on $(1,\\infty)$ is in $L^p$ for $p > 1$ but not $L^1$. $f(x) = 1/\\sqrt{x}$ on $(0,1)$ is in $L^1$ but not $L^2$. The two failures live on opposite ends — large-$x$ tail vs singularity.</p>" +
      "<h4>Trick</h4>" +
      "<p>'Large $p$ controls tails; small $p$ controls singularities.' On a finite measure space tails don't exist, so larger $p$ is strictly stronger.</p>"
  },

  // ─── RADON–NIKODYM / ABSOLUTE CONTINUITY ───────────────────────────
  {
    id: "rn01", topic: "Radon–Nikodym",
    prompt: "State **Radon–Nikodym**. What does $\\nu \\ll \\mu$ mean and why is σ-finiteness essential?",
    answer:
      "<h4>Statement</h4>" +
      "<p>Let $\\mu, \\nu$ be σ-finite measures on $(X,\\mathcal{A})$ with $\\nu \\ll \\mu$ (i.e. $\\mu(E) = 0 \\Rightarrow \\nu(E) = 0$). Then there exists a measurable $f: X \\to [0,\\infty]$, unique $\\mu$-a.e., with $\\nu(E) = \\int_E f \\, d\\mu$ for all $E \\in \\mathcal{A}$. We write $f = d\\nu/d\\mu$.</p>" +
      "<h4>Failure without σ-finiteness</h4>" +
      "<p>Take $X = [0,1]$, $\\mu = $ counting measure, $\\nu = $ Lebesgue. Then $\\nu \\ll \\mu$ trivially (only $\\mu$-null set is $\\emptyset$). But no density $f$ exists: $\\nu(\\{x\\}) = 0$ would force $f(x) = 0$ everywhere, so $\\int f \\, d\\mu = 0 \\ne \\nu([0,1])$.</p>" +
      "<h4>Trick</h4>" +
      "<p>$\\nu \\ll \\mu$ is the qualitative version; the density is the quantitative version. The bridge needs σ-finiteness so we can decompose $X$ into countably many finite-measure pieces and assemble the density piece-by-piece."
  },
  {
    id: "rn02", topic: "Radon–Nikodym",
    prompt: "Connect Radon–Nikodym to **probability density functions**. What does $\\mathbb{P}(X \\in E) = \\int_E f \\, d\\lambda$ say in measure-theoretic language?",
    answer:
      "<p>$X$ is a real-valued random variable on $(\\Omega,\\mathcal{F},\\mathbb{P})$. Its <em>law</em> $\\mathcal{L}(X) := \\mathbb{P} \\circ X^{-1}$ is a probability measure on $(\\mathbb{R},\\mathcal{B})$. Saying '$X$ has density $f$ wrt Lebesgue measure' means $\\mathcal{L}(X) \\ll \\lambda$ and $f = d\\mathcal{L}(X)/d\\lambda$.</p>" +
      "<h4>Singular case</h4>" +
      "<p>If $X$ is discrete (e.g. Bernoulli), $\\mathcal{L}(X)$ is supported on a countable set, hence singular wrt $\\lambda$. No Lebesgue density exists. Radon–Nikodym still applies — wrt counting measure on $\\{0,1\\}$ — and the density is the PMF.</p>" +
      "<h4>Mixed case</h4>" +
      "<p>$X = $ income, with point mass at 0 (unemployed) and a continuous distribution on $(0,\\infty)$. Lebesgue density doesn't exist. Decompose $\\mathcal{L}(X) = p \\delta_0 + (1-p) \\nu_{cts}$ via Lebesgue decomposition.</p>"
  },

  // ─── PRODUCT MEASURES / FUBINI ─────────────────────────────────────
  {
    id: "fb01", topic: "Fubini–Tonelli",
    prompt: "Distinguish **Tonelli** from **Fubini**. Which hypothesis differs?",
    answer:
      "<h4>Tonelli</h4>" +
      "<p>If $f: X \\times Y \\to [0,\\infty]$ is measurable wrt the product σ-algebra (and the measures are σ-finite), then both iterated integrals equal the double integral: $\\int_X \\int_Y f \\, d\\nu \\, d\\mu = \\int_Y \\int_X f \\, d\\mu \\, d\\nu = \\int_{X\\times Y} f \\, d(\\mu \\otimes \\nu)$. <strong>No integrability needed</strong> — non-negativity carries the load.</p>" +
      "<h4>Fubini</h4>" +
      "<p>If $f: X \\times Y \\to \\mathbb{R}$ is integrable wrt $\\mu \\otimes \\nu$ (i.e. $\\int |f| < \\infty$), then both iterated integrals equal the double integral.</p>" +
      "<h4>Workflow</h4>" +
      "<p>To swap iterated integrals for a signed/complex $f$: <strong>first apply Tonelli to $|f|$</strong> to verify integrability. <strong>Then apply Fubini to $f$</strong>.</p>"
  },
  {
    id: "fb02", topic: "Fubini–Tonelli",
    prompt: "Give a counterexample where iterated integrals exist and are unequal — i.e. Fubini's hypothesis fails.",
    answer:
      "<h4>Classical example</h4>" +
      "<p>$f(x,y) = \\frac{x^2 - y^2}{(x^2+y^2)^2}$ on $[0,1]^2$, defined arbitrarily on the diagonal $x=y=0$. Direct computation:</p>" +
      "<p>$\\int_0^1 \\!\\int_0^1 f(x,y) \\, dy \\, dx = \\frac{\\pi}{4}, \\quad \\int_0^1 \\!\\int_0^1 f(x,y) \\, dx \\, dy = -\\frac{\\pi}{4}.$</p>" +
      "<p>Both iterated integrals exist (each inner integral is finite), but they are unequal. Why? Because $\\int |f| = \\infty$ — the function is not integrable wrt the product measure, so Fubini doesn't apply.</p>" +
      "<h4>Trick</h4>" +
      "<p>Always check $\\int |f| < \\infty$ before swapping. Existence of the iterated integrals is <em>not</em> a substitute. The mass cancels in different orders, giving different signed sums."
  },

  // ─── MISC EXAM-FREQUENT ────────────────────────────────────────────
  {
    id: "mi01", topic: "Borel–Cantelli",
    prompt: "State both **Borel–Cantelli lemmas** and give a concrete probabilistic application of each.",
    answer:
      "<h4>BC1 (easy direction)</h4>" +
      "<p>$\\sum_n \\mu(A_n) < \\infty \\Rightarrow \\mu(\\limsup A_n) = 0$. " +
      "(In probability: only finitely many $A_n$ occur, almost surely.)</p>" +
      "<h4>BC2 (independence required)</h4>" +
      "<p>If $\\{A_n\\}$ are independent and $\\sum_n \\mathbb{P}(A_n) = \\infty$, then $\\mathbb{P}(\\limsup A_n) = 1$.</p>" +
      "<h4>Applications</h4>" +
      "<p>(a) <em>Strong law of large numbers, fast version.</em> Use BC1 to show that for iid $X_n$ with $\\mathbb{E}[X^4] < \\infty$, $\\frac{S_n}{n} \\to \\mathbb{E} X$ a.s. (Markov + 4th moment + BC1).</p>" +
      "<p>(b) <em>Recurrence of simple random walk on $\\mathbb{Z}$.</em> $\\mathbb{P}(S_n = 0) \\sim 1/\\sqrt{n}$, so $\\sum \\mathbb{P}(S_n = 0) = \\infty$. With independence (which fails for the same indicator events!), BC2 would give recurrence — actually we need more care, but the heuristic is BC2.</p>"
  },
  {
    id: "mi02", topic: "Egorov / Lusin",
    prompt: "State **Egorov's theorem** and **Lusin's theorem**, and explain what they buy you.",
    answer:
      "<h4>Egorov</h4>" +
      "<p>On a finite measure space, if $f_n \\to f$ a.e., then for every $\\varepsilon > 0$ there is a measurable $E$ with $\\mu(E) < \\varepsilon$ such that $f_n \\to f$ <strong>uniformly</strong> on $E^c$.</p>" +
      "<p><em>Pointwise a.e. convergence becomes uniform convergence away from a small bad set.</em></p>" +
      "<h4>Lusin</h4>" +
      "<p>For Lebesgue-measurable $f: \\mathbb{R} \\to \\mathbb{R}$ and $\\varepsilon > 0$, there is a closed set $E$ with $\\lambda(E^c) < \\varepsilon$ such that $f|_E$ is <strong>continuous</strong>.</p>" +
      "<p><em>Measurable functions are 'almost continuous' — continuous after deleting a small bad set.</em></p>" +
      "<h4>Slogan (Littlewood's three principles)</h4>" +
      "<p>Every measurable set is nearly a finite union of intervals. Every measurable function is nearly continuous. Every convergent sequence of measurable functions is nearly uniformly convergent. <em>Egorov + Lusin formalize the latter two.</em>"
  },
  {
    id: "mi03", topic: "Differentiation",
    prompt: "State the **Lebesgue differentiation theorem** and connect it to the **fundamental theorem of calculus** in this setting.",
    answer:
      "<h4>Lebesgue differentiation</h4>" +
      "<p>For $f \\in L^1_\\mathrm{loc}(\\mathbb{R}^n)$, almost every $x$ is a <em>Lebesgue point</em>: $\\frac{1}{|B_r(x)|}\\int_{B_r(x)} f \\, d\\lambda \\to f(x)$ as $r \\to 0$.</p>" +
      "<h4>FTC connection</h4>" +
      "<p>In $\\mathbb{R}$: if $F(x) = \\int_a^x f(t) \\, dt$ for $f \\in L^1$, then $F'(x) = f(x)$ a.e. — that's exactly the differentiation theorem applied to half-balls.</p>" +
      "<h4>Sharper: AC functions</h4>" +
      "<p>$F$ is absolutely continuous iff $F$ is the integral of its (a.e.-existing) derivative: $F(x) - F(a) = \\int_a^x F'(t) \\, dt$. Cantor's staircase has $F'=0$ a.e. but $F(1)-F(0)=1$ — fails to be AC, hence the FTC fails.</p>"
  },

  // ─── SAMPLING + PROBABILITY GLUE (relates to his SOC work) ─────────
  {
    id: "pr01", topic: "Probability glue",
    prompt: "What is a **probability space**? Define $\\sigma(X)$ for a random variable $X$, and explain $\\mathbb{E}[Y \\mid \\mathcal{G}]$ measure-theoretically.",
    answer:
      "<h4>Probability space</h4>" +
      "<p>$(\\Omega, \\mathcal{F}, \\mathbb{P})$: a sample space, an event σ-algebra, and a probability measure ($\\mathbb{P}(\\Omega) = 1$).</p>" +
      "<h4>$\\sigma(X)$</h4>" +
      "<p>Smallest σ-algebra on $\\Omega$ making $X$ measurable: $\\sigma(X) := \\{X^{-1}(B) : B \\in \\mathcal{B}(\\mathbb{R})\\}$. It encodes 'what you know if you observe $X$'.</p>" +
      "<h4>Conditional expectation</h4>" +
      "<p>For $Y \\in L^1$ and a sub-σ-algebra $\\mathcal{G} \\subset \\mathcal{F}$, $\\mathbb{E}[Y \\mid \\mathcal{G}]$ is the unique (a.s.) $\\mathcal{G}$-measurable random variable $Z$ with $\\int_A Z \\, d\\mathbb{P} = \\int_A Y \\, d\\mathbb{P}$ for every $A \\in \\mathcal{G}$.</p>" +
      "<p>Existence by Radon–Nikodym: define $\\nu(A) := \\int_A Y \\, d\\mathbb{P}$ for $A \\in \\mathcal{G}$; $\\nu \\ll \\mathbb{P}|_\\mathcal{G}$, so $d\\nu/d(\\mathbb{P}|_\\mathcal{G})$ exists and is the conditional expectation.</p>" +
      "<h4>Why this matters in SOC</h4>" +
      "<p>Bellman's principle: $V(x_t) = \\inf_u \\mathbb{E}[c(x_t, u) + V(x_{t+1}) \\mid x_t]$. The conditional expectation operator <em>is</em> the dynamic-programming step."
  },
  {
    id: "pr02", topic: "Probability glue",
    prompt: "Why does **SAA** (Sample Average Approximation) have a measure-theoretic justification? What kind of convergence?",
    answer:
      "<p>The true objective is $J(u) = \\mathbb{E}_\\varepsilon[c(u,\\varepsilon)] = \\int c(u,\\varepsilon) \\, d\\mathbb{P}(\\varepsilon)$. The SAA estimator with $N$ samples is $J_N(u) = \\frac{1}{N}\\sum_i c(u,\\varepsilon_i)$.</p>" +
      "<h4>What converges, and how?</h4>" +
      "<p>(a) <em>Pointwise SLLN:</em> for fixed $u$, $J_N(u) \\to J(u)$ a.s. by the strong law (assuming $c(u,\\cdot) \\in L^1$).</p>" +
      "<p>(b) <em>Uniform convergence on compact sets:</em> if $u \\mapsto c(u,\\varepsilon)$ is continuous and $\\sup_{u \\in K} |c(u,\\varepsilon)|$ is integrable in $\\varepsilon$, then $\\sup_{u \\in K} |J_N(u) - J(u)| \\to 0$ a.s. (Glivenko–Cantelli class.)</p>" +
      "<p>(c) <em>Argmin convergence:</em> from (b), if $J$ has a unique minimizer on $K$, the SAA argmins $\\hat u_N \\to u^*$ a.s. (epi-convergence).</p>" +
      "<h4>Slogan</h4>" +
      "<p>SAA replaces an integral against $\\mathbb{P}$ with an integral against the empirical measure $\\hat{\\mathbb{P}}_N = \\frac{1}{N}\\sum_i \\delta_{\\varepsilon_i}$. The Lebesgue/Radon–Nikodym machinery says when this swap is harmless."
  },
];

// Topics in display order.
window.TOPICS = [
  "all",
  "σ-algebras",
  "Measurable functions",
  "Convergence theorems",
  "Lp spaces",
  "Radon–Nikodym",
  "Fubini–Tonelli",
  "Borel–Cantelli",
  "Egorov / Lusin",
  "Differentiation",
  "Probability glue",
];
